### ISSUE TITLE
Cookie

### ISSUE THREAD

**Issue by avesgit** [Imangazaliev/DiDOM#1]
Можно сделать установку кук при file_get_content?  Погуглил вроде можно такую фичу реализовать http://stackoverflow.com/questions/3431160/php-send-cookie-with-file-get-contents

При написании парсера было все гуд только потом начало выбивать в файрфоксе вот такое 
Firefox определил, что сервер перенаправляет запрос на этот адрес таким образом, что он никогда не завершится.

    Эта проблема может возникать при отключении или запрещении принятия кук.

Скорее всего увидели много запросов на сервер и вробуили куки

И еще вопрос нельзя ли урлы читать через курл с отправкой всех нужных заголовков итд и будет самый лучший парсер

**Comment by Imangazaliev** [comment]
Для загрузки будет лучше использовать [Guzzle](https://github.com/guzzle/guzzle), а затем загружать в парсер как строку
