### ISSUE TITLE
DOMDocument parse html error

### ISSUE THREAD

**Issue by garguntua** [Imangazaliev/DiDOM#101]
Hi, I parse the html like this:
[PHP_DOMDocument_Bug:](https://raw.githubusercontent.com/garguntua/tools/master/PHP_DOMDocument_Bug)

this html has been parse to two html Element.
PHP out put like this [PHP_DOMDocument_Bug:](https://raw.githubusercontent.com/garguntua/tools/master/PHP_DOMDocument_Bug)
I need your help,thanks so much.

**Comment by Imangazaliev** [comment]
Hi. Please checkout this issue #97

**Comment by garguntua** [comment]
Thanks so much,
php_html_parser lib is too slow, in swoole,this lib qps is 50(1 CPU ,2G ).
In my test,DiDom qps is 700(very good),but the DomDocument(Libxml php extension) has this bug. 
I choose goquery(golang) to do this project,not php.
thank you again.
