### ISSUE TITLE
DiDom\Document::load expects parameter 4 to be integer, string given

### ISSUE THREAD

**Issue by jordymeow** [Imangazaliev/DiDOM#107]
Hello,

I developed a plugin for WordPress using DiDom as its DOM parser. It reads the content of the generated HTML page and modifies some parts of it.

It works great, but for some people, it doesn't, and it is always the same error message: DiDom\Document::load expects parameter 4 to be integer, string given.

It's very hard for me to propose a solution to those users, even for me, this error message is quite cryptic. So basically, would it be possible to enhance this error message, to understand exactly what is wrong? This error is internal to DiDom, so it would be good to know what is wrong with the input, basically that the HTML markup is wrong or something else. Right now I have no idea except trying another parser, but since DiDom works fast and nicely, I would rather spend a bit more time here understanding how to go around this issue.

Thanks a lot :)

**Comment by Imangazaliev** [comment]
Hi. The fourth parameter must be an integer, yes (see [src/DiDom/Document.php#L262](https://github.com/Imangazaliev/DiDOM/blob/master/src/DiDom/Document.php#L262))

Could you show your code?

**Comment by jordymeow** [comment]
I am always using it the same way, like this:
`$html = new Document( $buffer );`
The _buffer_ represents a whole HTML page generated by WordPress.

You can see the whole code here:
https://plugins.trac.wordpress.org/browser/gallery-custom-links/trunk

DiDom is used here in this part:
https://plugins.trac.wordpress.org/browser/gallery-custom-links/trunk/mgcl_core.php

Do you see something that I should do or not do? Thanks a lot, @Imangazaliev :)

**Comment by Imangazaliev** [comment]
Hmm, it's really strange. Could you open `vendor/imangazaliev/didom/src/DiDom/Document.php` at your project and dump `$options` variable before and after this code (lines 256 and 261):

```php
if ($options === null) {
    // LIBXML_HTML_NODEFDTD - prevents a default doctype being added when one is not found
    $options = LIBXML_HTML_NODEFDTD;
}
```

**Comment by mnoskov** [comment]
It means, that PHP casts an undefined constant to string, because it is not defined. This happens when libxml version lower than 2.7.8 or PHP version lower than 5.4.

**Comment by Imangazaliev** [comment]
@mnoskov yeah, I think the same

**Comment by jordymeow** [comment]
I was waiting for more users to encounter this issue, but what you said helps a lot @mnoskov.

**Comment by Imangazaliev** [comment]
@jordymeow you can pass 0 to $options to `loadHtml()` for workaround:

```php
$document->loadHtml($html, 0);
```

**Comment by Imangazaliev** [comment]
> PHP version lower than 5.4

@mnoskov, I think it is not, because the minimum version for DiDOM is 5.4.

**Comment by Imangazaliev** [comment]
If don't pass any option to `loadHtml()` method DiDOM uses `LIBXML_HTML_NODEFDTD` by default. As @mnoskov said, probably LIBXML_HTML_NODEFDTD is not defined, so on line 259 of Document.php the $options variable becomes a string `"LIBXML_HTML_NODEFDTD"` (this behaviour is deprecated since PHP 7.2, see http://php.net/manual/en/migration72.deprecated.php, https://wiki.php.net/rfc/deprecate-bareword-strings). You should get a notice "PHP Notice: Use of undefined constant LIBXML_HTML_NODEFDTD", but I think in your case PHP ignores notices and warnings and shows only exceptions and fatal error errors. You can configure it via `error_reporting()` function or in `php.ini`.

**Comment by jordymeow** [comment]
Unfortunately, this is happening on the installs of the users of my plugin, and I can't ask them to debut much, it's too difficult and obscure for most of them. I didn't encounter the issue myself. Thanks anyway, the "0" really helped :)
