### ISSUE TITLE
Selector not found

### ISSUE THREAD

**Issue by oxfn** [Imangazaliev/DiDOM#109]
Hello.
Trying to parse this doc http://squad.pw/tmp/knives.html.
`$doc->find('ul.main-menu')` returns an empty array.

**Comment by Imangazaliev** [comment]
Hi. Try to dump the HTML of your document and check that it's loaded correctly:

```php
var_dump($doc->html());
```

**Comment by oxfn** [comment]
Yeah, I see that site loaded from script is very different from `wget`-ed one. Thank you
