### ISSUE TITLE
Креш при селекторе "h1.post-title a:first"

### ISSUE THREAD

**Issue by nullproduction** [Imangazaliev/DiDOM#11]
Ошибся и вместо  селектора has("h1.post-title a:first-child") написал has("h1.post-title a:first") и получил 500 ошибку сервера без вывода ошибки в php. DiDOM юзаю в laravel 5.1, дебагер включен.
Понятно что сам написал неправильно селектор, но хотелось бы понять почему 500 ошибка вместо эксепшена?

**Comment by nullproduction** [comment]
Протестировал еще, насколько поменял 500 ошибка происходит если Query.php не может разобрать селектор, возможно стоит сделать отдельный метод который валидирует сам селектор и возвращает bool в зависимости от того валидный он или нет

**Comment by Muhammad97** [comment]
Причина бага найдена и будет исправлена в ближайшее время

**Comment by Imangazaliev** [comment]
Исправлено: [fd8911f](https://github.com/Imangazaliev/DiDOM/commit/fd8911faed2a817b41cb7ba09a8d7f88681ee33d). Теперь выбрасывает исключение `RuntimeException`.
