### ISSUE TITLE
Encoding issues

### ISSUE THREAD

**Issue by Rolige** [Imangazaliev/DiDOM#111]
Hi,

There is a couple of issues in the encoding, and I can't find the way to unformat the html content actually the final content change all HTML entities to the equivalent, eg, `Don&#039;t` comes to be as `Don't`.

The problem is that sometimes we need show HTML code, eg, if I use the code:
```html
This is an example link: &lt;a href=&quot;#link&quot;&gt;example link&lt;/a&gt;
```
With this code I'm trying to render this:
```html
This is an example link: <a href="#link">example link</a>
```
But after of parse the dom the result will be:
This is an example link: [example link](#)

Is there any way to omit the format?

**Comment by Imangazaliev** [comment]
What do you mean by "render"? Could you show your code?

**Comment by Rolige** [comment]
Try with this code:
```php
<?php

require dirname(__FILE__).'/vendor/autoload.php';

$html = 'This is an example link: &lt;a href=&quot;#link&quot;&gt;example link&lt;/a&gt;. And this is a real link: <a href="#link">example link</a>';

echo $html;
echo "\n\n";

$dom = new DiDom\Document($html);
$a = $dom->find('a')[0];
$a->setAttribute('target', '_blank');
$new_html = $dom->html();

echo $new_html;
```

Code before use DiDom:
```html
This is an example link: &lt;a href=&quot;#link&quot;&gt;example link&lt;/a&gt;. And this is a real link: <a href="#link">example link</a>
```

Code after use DiDom:
```html
<html><body><p>This is an example link: &lt;a href="#link"&gt;example link&lt;/a&gt;. And this is a real link: <a href="#link" target="_blank">example link</a></p></body></html>
```

My point here is, the library has changed an escaped quotes,
from `href=&quot;#link&quot;`  
to `ref="#link"`

So, there is a way/option to untouch the original code in this aspect?

**Comment by Imangazaliev** [comment]
I think it's an issue of PHP DOM extention. I really don't know how to fix it. I played with your code and tried several ways, but didn't get any result. I found [a question](https://stackoverflow.com/questions/8411865/prevent-php-dom-from-decoding) on StackOverflow, it's not related to your case, but possibly it will be helpful.

**Comment by Rolige** [comment]
I see, but according to your referrer of StackOverflow *Gordon* said that this was reported before for XML and was marked as "Not A Bug".
