### ISSUE TITLE
Random user agent

### ISSUE THREAD

**Issue by msenyil** [Imangazaliev/DiDOM#112]
How can I add random user agents?

**Comment by Imangazaliev** [comment]
Hi. DiDom not intended to load documents from a file or from the Internet. This feature was added only for some convenience. For more flexibiliry you need to use cURL or special libraries (e.g. [Guzzle](https://github.com/guzzle/guzzle) or [php-curl-class](https://github.com/php-curl-class/php-curl-class)) and then pass loaded HTML or XML to a document.
