### ISSUE TITLE
www.amazon.co.jp

### ISSUE THREAD

**Issue by newley1105** [Imangazaliev/DiDOM#115]
url: www.amazon.co.jp
`var $parent=$('<div class="nav-subcats"></div>').appendTo(flyout.elem());`
$document = new Document($content);
$document->html()
`var $parent=$('<div class="nav-subcats"></script></div>').appendTo(flyout.elem());`

**Comment by Imangazaliev** [comment]
Please, describe your issue, otherwise I will have to close it.
