### ISSUE TITLE
Преобразовывает в текст без пробелов

### ISSUE THREAD

**Issue by PSalador** [Imangazaliev/DiDOM#116]
При преобразовании html с внутренними тегами в текст получаем текст без пробелов.
```php
$html = '<ul><li>Первый</li><li>Второй</li><li>Третий</li><li>Четвертый</li></ul>';
$document = new Document($html);
$text = $document->text();
```
Получаем `ПервыйВторойТретийЧетвертый`
Как сделать чтобы пробелы были между словами?

**Comment by Imangazaliev** [comment]
```php
// найти элементы li и получить их содержимое
$itemsText = $document->find('li::text');

$text = implode(' ', $itemsText);
```

**Comment by PSalador** [comment]
Это понятно. Но я привел частный случай - неизвестно какие теги внутри html и их вложенность.
Мне нужно чтобы ` $document->text(); ` (или какая-нибудь другая команда) выводили текст с пробелами меду тегами.

**Comment by Imangazaliev** [comment]
Метод `text()` возвращает текстовое содержимое узла, которое включает в себя содержимое всех элементов. Как вариант, можно использовать селектор `*`, но нужно учитывать, что в таком случае текст будет дублироваться.

**Comment by PSalador** [comment]
Да так можно вытащить текст разделенный пробелами.
```
        $itemsText = $document->find('*');
        $text='';
        foreach ($itemsText as $itemText){
            $text.=$itemText->text();
        }
```
Но в дубли попадает сдвоенный текст без пробелов, который сложно вычистить.

**Comment by PSalador** [comment]
Попробовал через регулярку - вроде то что нужно.
```php
$html = '<ul><li>Первый</li><li>Второй</li><li>Третий</li><li>Четвертый</li></ul>';
$document = new Document($html);
$innerHtml = $document->html();
preg_match_all("#<.+?>(.[^<>]+?)<.+?>#s", $innerHtml, $textArray);
$text = implode(" ", $textArray[1]);
```
