### ISSUE TITLE
function xpath() on array

### ISSUE THREAD

**Issue by 5brothers** [Imangazaliev/DiDOM#118]
Добрый день

Прошу прощения, но никак не могу разобраться в логике. Есть такой код:

```
<table class="infoBox">
<td class="smallText 4" style="padding:0;" valign="top" width="100%"><table><tbody><tr><td><a href="https://www.kupiklubok.ru/alpaka-royal-c-527_639_640.html"><img src="images/alpaca-royal-catalog-kupiklubok.jpg" border="0" alt="Альпака Роял; 30% альпака, 15% шерсть, 55% акрил, 250м/100г (Alize)" title=" Альпака Роял; 30% альпака, 15% шерсть, 55% акрил, 250м/100г (Alize) " width="150px" height="91px"></a></td><td><a style="padding-left: 20px;" href="https://www.kupiklubok.ru/alpaka-royal-c-527_639_640.html"><b>Альпака Роял; 30% альпака, 15% шерсть, 55% акрил, 250м/100г (Alize)</b></a></td></tr></tbody></table></td>
...

...
</table>
```

**td class="smallText 4"** в таблице повторяется много раз, соответственно имеет разные ссылки, т.е. массив

Пытаюсь получить первую ссылку внутри td из таблицы:

`$links = $document->find('table.infoBox')[4]->find('td.4')->xpath('//a')[0];`

Но выдает ошибку: **Fatal error: Uncaught Error: Call to a member function xpath() on array in..**

Подскажите пожалуйста, почему? Ведь: Находим таблицу с классом infoBox, находим td с классом 4, далее, внутри этого td пытаюсь через xpath найти первую ссылку (при помощи [0] ). В чем я ошибаюсь?

PS

Конструкция **$links = $document->find('table.infoBox')[4]->find('td.4 a')** работает и находит обе ссылки..

Но конструкция с first уже ничего не находит: **$links = $document->find('table.infoBox')[4]->first('td.4 a');** Хотя по логике, как мне видится, должна найти как раз первый td с классом 4 и получить оттуда ссылку

**Comment by 5brothers** [comment]
Очень прошу подскажите, голова отваливается уже, не понимаю как нужно сдлеать

**Comment by Imangazaliev** [comment]
Наверное потом, что такого элемента там просто нет?

Что касается ошибки "Fatal error: Uncaught Error: Call to a member function xpath() on array in.", то второй вызов `find` так же возвращает массив, у которого вы пытаетесь вызвать метод `xpath`. Нужно либо использовать `first`, либо получить конкретный элемент из массива.

**Comment by 5brothers** [comment]
Спасибо, разобрался

И хотелось бы еще поинтересоваться по поводу загрузки динамически загружающегося сайта, т.е.  DOM строиться уже при загрузке сайта скриптами, а по факту нужного html кода там нет, и пасрер соответственно ничего не видит. 

Возможно ли как то парсить такие страницы?

**Comment by Imangazaliev** [comment]
Это можно сделать с помощью Headless Chrome: получить с его помощью HTML, а потом передать в DiDOM
