### ISSUE TITLE
Не работает поиск елементов по значению атрибута

### ISSUE THREAD

**Issue by nullproduction** [Imangazaliev/DiDOM#12]
Сделал специальный упрощенный пример:

```
$html = '<html><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta property="og:title" content="Title" /></head></html>';

        $document = new \DiDom\Document($html);
        $elements = $document->find('meta[property=og:title]');
        $element = $elements[0];
        echo $element->getAttribute('content');
```

Выводит:
```
text/html; charset=UTF-8
```

То есть конструкция [property=og:title] не учитывается

**Comment by devmru** [comment]
Его просто нету.
```php
foreach ($document->find('meta') as $meta) {
   if($meta->attr('property')=='og:title'){
      $elements = $meta;
   }
}
```

**Comment by nullproduction** [comment]
@devmru пичаль. а в тестах QueryTest.php есть тестирование такой конструкции textarea[name=product-description] поэтому думал что должно работать.

Такой костыль как ты предлагаешь не хочется юзать, перешел пока на бибилиотеку DomCrawler от симфони, она все селекторы jquery поддерживает

**Comment by Imangazaliev** [comment]
Исправлено: [1635d4a](https://github.com/Imangazaliev/DiDOM/commit/dd0e5eb2f114d6e5d31266138a35d7a424faf249). Необходимо обновиться до 1.4.1

**Comment by nullproduction** [comment]
@Imangazaliev спасибо за столь оперативные фиксы. очень круто

**Comment by devmru** [comment]
спасибо!
