### ISSUE TITLE
How to check an element by its number?

### ISSUE THREAD

**Issue by acuna-public** [Imangazaliev/DiDOM#120]
Hello! Thanks for your great library. I need to check if element exists in the DOM. I'm using SimpleXMLDom now and check it like

    if ($td = $tr->find ('.class', 0)) {
        // operations with $td
    }

Seems that DiDom allows to use `has ()` method for this, but there's not useful when I need to create variables like this to work with, and first of all it's impossible to change tons of my code manually, so I have a big hope that it's possible, but simply I can't find it in documentation. Thanks!

**Comment by Imangazaliev** [comment]
Hi. The first way is to get all elements and use `array_key_exists` function:

```php
$elements = $tr->find('class');

if (array_key_exists(0, $elements)) {
   // ...
}
```

And the second, which I prefer, is to use `nth-child` pseudoclass:

```php
if ($tr->has('.class:nth-child(0)')) {
   // ...
}
```

**Comment by acuna-public** [comment]
Ah, thanks for your answer, but seems I need to use an regular expressins to replase the tonns of my code, so I need to think about it...

And another problem is I can't find the method fo removing all element nodes. I'm using my own method for this now

    function remove ($what, $where) {
      
       foreach ($where->find ($what) as $el)
         $where = $el->remove ();
      
       return $where;
      
    }

but think It'll be nice to implement it out of the box for not to ivent own bicycles.

**Comment by Imangazaliev** [comment]
Ok, I will think about it

**Comment by acuna-public** [comment]
Nice! But I have another problems with it (some tags text is empty), so seems that I'll start to write my own compatible with SimpleHTMLDom library...
