### ISSUE TITLE
Incorrect parsing when string contains BOM symbol

### ISSUE THREAD

**Issue by koteezy** [Imangazaliev/DiDOM#121]
If you create a class, and pass it an html-string that contains a BOM character - somewhere lost HEAD.

I solved this problem, so:

`
$validHtmlString = preg_replace( '/\x{FEFF}/u', '', $html );
`

Maybe we should do this on your side?

**Comment by Imangazaliev** [comment]
Hi. I will check it out

**Comment by Imangazaliev** [comment]
I think you solution is correct. Also you can save a file in UTF-8 or use `mb_convert_encoding` from `UTF-16` to `UTF-8`.
