### ISSUE TITLE
Перекодирование ссылок UTF8

### ISSUE THREAD

**Issue by soulcreate** [Imangazaliev/DiDOM#122]
Как можно обратно декодировать ссылки с utf8 символами?
Никак не пойму. Не нашел настройку, отключающую данную функцию.
Не получилось также декодировать вручную:
```
$find->href = urldecode($find->href);
```
Ссылку вида `site.com/[[~8]]` перекодирует в `site.com/%5B%5B~8%5D%5D`
Как это можно отключить?

PS: старый добрый  simplehtmldom помог:
```
foreach($html->find('a') as $a){
    $a->href = urldecode($a->href);
}
```

**Comment by Imangazaliev** [comment]
Думаю это особенность самого DOMDocument, нужно копать в эту сторону.

**Comment by Globulopolis** [comment]
rawurldecode() вам в помощь.
