### ISSUE TITLE
Переименовать тэг

### ISSUE THREAD

**Issue by soulcreate** [Imangazaliev/DiDOM#123]
Никак не пойму, как можно переименовать тэг. Возможно ли это вообще?
```
$element->tag = 'div';
```
Вот по такому примеру

**Comment by Imangazaliev** [comment]
Нет, это невозможно. Можно создать новый элемент с теми же атрибутами и содержимым:

```php
$span = $document->first('span');

$div = new Element('div', null, $span->attributes());

$div->setInnerHtml($span->innerHtml());
```

**Comment by soulcreate** [comment]
а можно ли заменить этот спан вновь созданным дивом? Спасибо за оперативный ответ!

**Comment by Imangazaliev** [comment]
Да, можно:
```php
$span->replace($div);
```
