### ISSUE TITLE
Update matrix for travis

### ISSUE THREAD

**Issue by Smolevich** [Imangazaliev/DiDOM#124]
Do you have plan to update matrix for travis ?
I propose to add php 7.1, 7.2, 7.3
Do you have plans to use coveralls.io for calculating code coverage by tests?
I can help and prepare PR.
Maybe to add supporting for [Github Actions](https://help.github.com/en/articles/about-github-actions) as additional ci?

**Comment by Imangazaliev** [comment]
> Do you have plan to update matrix for travis ?
Done

> Do you have plans to use coveralls.io for calculating code coverage by tests?
No

> Maybe to add supporting for Github Actions as additional ci?
No
