### ISSUE TITLE
Can't use multiple css :not pseudo elements

### ISSUE THREAD

**Issue by timurziev** [Imangazaliev/DiDOM#125]
For example. When I try to use it like $this->document->loadHtml($html)->find('.class1:not(.class2):not(.class3)') etc.

**Comment by Imangazaliev** [comment]
DiDOM doesn't support multiple pseudoclasses in CSS select now, maybe I will add it later, in shaa Allah.

**Comment by Imangazaliev** [comment]
I forgot to say that while this feature is not implemented, you can use XPath.

**Comment by Imangazaliev** [comment]
Implemented in [1.17](https://github.com/Imangazaliev/DiDOM/releases/tag/1.17).
