### ISSUE TITLE
Как вставить элемент, не child? 

### ISSUE THREAD

**Issue by KarelWintersky** [Imangazaliev/DiDOM#126]
Есть список абзацев 
```
<p>... <p>
<p>...<p>
..
```
нужно после N-го абзаца вставить элемент (div) с заданным содержанием и сохранить результат:
```
$dom = new \DiDom\Document($text);
$child = new \DiDom\Element('div', '[inread=100]');
$selector = $dom->find('p:nth-child(4)')[0]->appendChild($child);
return $dom->html();
```
Создает структуру:
```
<p>... <div>[inread=100]</div></p>
```
А нужно 
```
<p>...</p>
<div>[inread=100]</div>
```
В ридми намёков не нашёл. 

Возможно ли сделать то, что мне нужно?

**Comment by Imangazaliev** [comment]
Для этого нужно создать текстовый узел:

```php
$child = $document->createTextNode('[inread=100]');
$selector = $dom->find('p:nth-child(4)')[0]->appendChild($child);
```

**Comment by KarelWintersky** [comment]
```
$document = new \DiDom\Document($text);
$child = $document->createTextNode('<div>[inread=100]</div>');
$document->find('p:nth-child(4)')[0]->appendChild($child);
$text = $document->html();
```
Дает результат типа:
```
<p><strong>Миф. При мигрени помогут прогулки на свежем воздухе и горячий душ</strong>&lt;div&gt;[inread=100]&lt;/div&gt;</p>
```
То есть элемент всё равно *внутри* абзаца, а мне нужно создать соседа:
```
<p>4th <p>
<div>[inread]</div>
<p>5th</p>
```

**Comment by KarelWintersky** [comment]
Можно конечно перебрать все элементы `$text` в цикле и вставить после нужного нужный блок, но мне это видится кривым решением.

**Comment by Imangazaliev** [comment]
Немного неправильно понял вопрос.

```
$child = $document->createTextNode('<div>[inread=100]</div>');
```
Не обратил внимания, что div должен остаться.

Можно получить 5-й элемент и, используя метод (DOMNode::insertBefore())[https://www.php.net/manual/en/domnode.insertbefore.php], вставить элемент до него. В случае, если нужно вставить элемент в конец, нужно будет использовать `appendChild()`. К сожалению, метода в `DiDom\Document` пока нет, поэтому придется пойти обходным путем:
```
$child = $document->createElement('div', '[inread=100]');
$insertBeforeNode =  $dom->find('p:nth-child(5)');

$document->getDocument()->insertBefore($child->getNode(), $insertBeforeNode->getNode());
```

**Comment by KarelWintersky** [comment]
Теперь я вас не понимаю :(
`$document ` как объявляется?

P.S. Можно ли рассчитывать, что метод появится? ;)

**Comment by Imangazaliev** [comment]
> $document -то мне как объявить?

Он ведь уже у вас есть:

```php
$document = new \DiDom\Document($text);
```

> Можно ли рассчитывать, что метод появится

Да, ин шаа Ллах.

**Comment by KarelWintersky** [comment]
Ларчик не так просто открывается :(

```
public function DOMNode::insertBefore (DOMNode $newnode, DOMNode $refnode = null) DOMNode
```
но Element->getNode() возвращает тип 
```
@return \DOMElement|\DOMText|\DOMComment|\DOMCdataSection
```

**Comment by KarelWintersky** [comment]
Мой код, в итоге:
```
    private function prepare_inread($text)
    {
        $document = new \DiDom\Document($text);

        $child = $document->createElement('div', '[inread=100]');

        $insertBeforeNode = $document->find('p:nth-child(5)')[0];
        $document->getDocument()->insertBefore($child->getNode(), $insertBeforeNode->getNode());

        return $document->html();
    }

```
Кидает эксепшен:
```
object(DOMException)#139 (7) {
  ["message":protected]=>
  string(15) "Not Found Error"
  ["string":"Exception":private]=>
  string(0) ""
  ["file":protected]=>
  string(61) "site_articles.php"
  ["line":protected]=>
  int(428)
  ["trace":"Exception":private]=>
  array(5) {
    [0]=>
    array(6) {
      ["file"]=>
      string(61) "site_articles.php"
      ["line"]=>
      int(428)
      ["function"]=>
      string(12) "insertBefore"
      ["class"]=>
      string(7) "DOMNode"
      ["type"]=>
      string(2) "->"
      ["args"]=>...
```

**Comment by KarelWintersky** [comment]
И еще очень хотелось бы метод, похожий на `html()`, но чтобы не оборачивал результат в 
```
<html><body>....</body></html>
```
Но сохранял (в отличие от `->text()` ) теги внутри.

Да, можно порезать регуляркой, но...

**Comment by KarelWintersky** [comment]
в итоге все кончилось вот таким ужасом:
```
 private function prepare_inread($text, $alias = '')
    {
        $html = '';

        $document = new \DiDom\Document();
        $document->loadHtml($text);

        $inread_after_node = 4;

        $step = 1;
        foreach ($document->find('body > *', Query::TYPE_CSS, false) as $item) {
            if ($step == $inread_after_node) {
                $html .= "INREAD_BLOCK";
            }

            $html .= $item->C14N() . PHP_EOL;

            $step++;
        }

        return $html;
    }
```
Но это совершенно несладко :(

Суть в том, что мне нужно взять блок HTML-текста и после 3 абзаца вставить код баннера. Или, в перспективе - после 3 абзаца и далее, через каждые 6.

Да, "абзацем" считается, к сожалению, не только `<p>`, а любая нода первого уровня вложенности (там может быть `<center><iframe>...` или даже `<blockquite><p>...<p></blockquite>`)

**Comment by KarelWintersky** [comment]
Хорошо было бы иметь что-то такое:

```
$document = new \DiDom\Document($text);
$child = $document->createNode('<div>[inread=100]</div>');
$document->find(':nth-child(4)')[0]->appendSibling($child);
$text = $document->html();
```

**Comment by Imangazaliev** [comment]
На днях посмотрю и отвечу, пока совсем нет времени.

**Comment by Imangazaliev** [comment]
> К сожалению, метода insertBefore в DiDom\Document пока нет

Собрался было добавить его и понял, что это можно реализовать используя `$document->getElement()->insertBefore(...);`.

> И еще очень хотелось бы метод, похожий на html(), но чтобы не оборачивал результат в ...

Если я правильно понял, можно сделать это так:

```php
$document->first('body')->innerHtml();
```

> Хорошо было бы иметь что-то такое:

Тогда это будет скорее два метода: `appendSiblingBefore` и `appendSiblingAfter`.

**Comment by KarelWintersky** [comment]
> что это можно реализовать используя 

Можно, наверное (мне не удалось, вроде бы). Лишняя функция-хэлпер не повредит ;-)

> $document->first('body')->innerHtml();

По моему, оно вырезает комментарии из кода. 

> Тогда это будет скорее два метода: appendSiblingBefore и appendSiblingAfter.

только за :)

**Comment by KarelWintersky** [comment]
bump!

**Comment by Imangazaliev** [comment]
Недавно пересматривал это issue :) думаю сделаю на выходных

**Comment by KarelWintersky** [comment]
Закрывает какой-нибудь из коммитов эту проблему?

**Comment by KarelWintersky** [comment]
@Imangazaliev , bump ;)

**Comment by Imangazaliev** [comment]
@KarelWintersky [сделал](https://github.com/Imangazaliev/DiDOM/releases/tag/1.16). Примеры можно глянуть [в тестах](https://github.com/Imangazaliev/DiDOM/blob/c2a8bd08679d2eec856782277267a48553322c7e/tests/ElementTest.php#L480).
