### ISSUE TITLE
404

### ISSUE THREAD

**Issue by OldGattsu** [Imangazaliev/DiDOM#127]
Здравствуйте.
Парсер спотыкается об несуществующую страницу (404). Можно ли это как-то отловить?

**Comment by Imangazaliev** [comment]
Привет. DiDOM не предназначен для загрузки документов из интернета, эта возможность добавлена для простейших случаев. Если требуется что-то сложнее (обработка ошибок, авторизация), лучше использовать cURL или обертки для него, типа Guzzle, после чего передавать загруженный HTML в DiDOM.
