### ISSUE TITLE
Warnings (PHP 5.6.14)

### ISSUE THREAD

**Issue by Romchik** [Imangazaliev/DiDOM#13]
На PHP 5.5 было все ок, а на 5.6.14 выдает предупреждения:

Warning: DOMNode::cloneNode(): ID ***** already defined in ***\vendor\imangazaliev\didom\src\DiDom\Document.php on line 72

**Comment by Imangazaliev** [comment]
Можете привести пример кода, при котором выбрасывается эта ошибка?

**Comment by Romchik** [comment]
```php
require_once( 'inc/DiDom/Document.php' );

use \DiDom\Document;

$document     = new Document( 'https://downloads.mariadb.org', TRUE );
$version_test = $document->find( '.span9.series' )[ 1 ]->find( '.buttons' )[ 0 ]->find( 'a' )[ 0 ]->text();
```

**Comment by Imangazaliev** [comment]
PHP 5.6.3, все работает

**Comment by Romchik** [comment]
Работать и у меня работает. Просто на 5.5.11 предупреждения не выпрыгивали, а на 5.6.14 появились.
