### ISSUE TITLE
Set attribute without value

### ISSUE THREAD

**Issue by cedricbdev** [Imangazaliev/DiDOM#131]
Is it possible to dynamically create an Element and set some attributes without values?

i.e:
```
<video controls autoplay>
  <source ...>
</video>
```
How to set "controls" and "autoplay"?

```
$video_tag = new \DiDom\Element('video');
$video_tag->attr('controls', STRING_VALUE_REQUIRED);
$video_tag->attr('autoplay', STRING_VALUE_REQUIRED);
```

**Comment by Imangazaliev** [comment]
Try to use `DOMDocument::createAttribute` and `DOMElement::setAttributeNode` methods (you should get `DOMDocument` and `DOMElement` objects wrapped by DiDOM using `DiDom\Document::getDocument()` and `DiDom\Element::getNode()` methods).

**Comment by cedricbdev** [comment]
Thank you for your answer! I'll take a look.
