### ISSUE TITLE
[RuntimeException]  Could not load file

### ISSUE THREAD

**Issue by SlavaFame** [Imangazaliev/DiDOM#133]
Пытаюсь парсить сайт prodoctorov.ru и возникает вот такая ошибка:

[RuntimeException] 
Could not load file https://prodoctorov.ru/ (0)
/home/f/mysite/public_html/test/vendor/imangazaliev/didom/src/DiDom/Document.php:389
#0: DiDom\Document->loadFile(string)
	/home/f/mysite/public_html/test/vendor/imangazaliev/didom/src/DiDom/Document.php:280
#1: DiDom\Document->load(string, boolean, string)
	/home/f/mysite/public_html/test/vendor/imangazaliev/didom/src/DiDom/Document.php:70
#2: DiDom\Document->__construct(string, boolean)
	/home/f/mysite/public_html/test/index.php:16

Пытаюсь хотя бы просто получить ссылки, но не выходит. Пример кода: 

`<?php` 
`require_once('vendor/autoload.php');`
`use  DiDom\Document;`
`$document = new Document("https://prodoctorov.ru/", true);`
`$images = $document->find('a');`
`foreach($images as $image) {`
`echo $image->href."<br>"; } ?>`

С чем это может быть связано? Ошибка сертификата или это какая-то защита от парсинга? С другими сайтами такой проблемы не возникало.

**Comment by Imangazaliev** [comment]
Привет. DiDOM не предназначен для загрузки документов из интернета, эта возможность добавлена для простейших случаев. Если требуется что-то сложнее (обработка ошибок, авторизация), лучше воспользоваться cURL или оберткой для него, типа Guzzle, после чего передавать загруженный HTML в DiDOM.
