### ISSUE TITLE
Метод matches не срабатывает на селекторах вида ".parent .element"

### ISSUE THREAD

**Issue by HDDen** [Imangazaliev/DiDOM#134]
Нужно собрать элементы на странице, прогнать их через функцию, но при этом исключать подпадающие под определенный селектор вида ".parent .element". С таким многоуровневым селектором match() не работает, поддерживается проверка только по собственному атрибуту - например, "div.classname" или "img[src*=".jpg"]".

```
// Собираем все элементы, 
$process_on = $document->find('.general-selector');

// Передаем собранные элементы в функцию по-одному
foreach ($process_on as $elem){
	
	// Сначала проверим, подпадает ли под исключающий селектор
	if ($elem->matches('.parent .class')){
		continue; // по идее, здесь обработка этого элемента должна прерываться, но нет.
	}

	// Не вышли из цикла - обрабатываем элемент
	handler($elem);
}
```

**Comment by Imangazaliev** [comment]
Метод `matches` предназначен для проверки элемента селектору. Для решения вашей задачи, можно использовать комбинацию `matches` + `find` или `matches` + `closest`.

**Comment by HDDen** [comment]
> Метод `matches` предназначен для проверки соответствия элемента селектору. Для решения вашей задачи, можно использовать комбинацию `matches` + `find` или `matches` + `closest`.

Здравствуйте!
Подскажите, пожалуйста, как использовать комбинацию "matches + find" для этой задачи?
