### ISSUE TITLE
Найти последнего ребенка

### ISSUE THREAD

**Issue by 5brothers** [Imangazaliev/DiDOM#135]
```
<div class="parent">
<div class="kid">первое</div>
<div class="kid">второе</div>
</div>
```

Как мне получить последний элемент и его содержимое? 
Прекрасно получается найти первого с методом first 
`$sostav = $document->find('.parent')[0]->first('.kid');`
Жаль не существует метода last
А с lastChild() упорно натыкается на массив и все, хотя какой массив может быть с одним последним элементом. Никак не могу понять, как находить последнего ребенка. 
Можете подсказать, пожалуйста?

**Comment by Imangazaliev** [comment]
> А с lastChild() упорно натыкается на массив и все

Не знаю, о каком массиве идет речь, но `lastChild()` возвращает последний **узел** (node), которым в данном случае является перенос строки между `<div class="kid">второе</div>` и `</div>`, нужно помнить об этом.

Для получение последнего элемента нужно использовать псевдокласс `:last-child`:

```php
<?php

// ...

$lastChild = $document->first('.parent')->first('.kid:last-child');
```
