### ISSUE TITLE
Html tags between <script> lost while parsed by DiDOM

### ISSUE THREAD

**Issue by badongdyc** [Imangazaliev/DiDOM#138]
my code is 
![2](https://user-images.githubusercontent.com/17975624/81884507-af960b80-95ca-11ea-9cc8-828ff6d8c5b6.png)
the output looks like this
![3](https://user-images.githubusercontent.com/17975624/81884605-e4a25e00-95ca-11ea-9f08-7495db68b727.png)
html tags between <script> lost, is this a bug ?

**Comment by Imangazaliev** [comment]
This issue is related to PHP DOM extension, not DiDOM. You should remove `<script>` tag by a regular expression before passing an HTML to DiDOM.
