### ISSUE TITLE
Page content uncomplete

### ISSUE THREAD

**Issue by lfaveur** [Imangazaliev/DiDOM#139]
Hi,
I was testing the script and I haven't got weird things ...
when I do
`
    $toto = new \DiDom\Document('https://www-old.elephorm.com/recherche', true);
    echo $toto;
`
I have not all the page : when I parse the file i can't find 

![image](https://user-images.githubusercontent.com/20400434/82665919-118eea80-9c35-11ea-83ae-a1fb93cfd8db.png)

Because when I save the page I have the complete data ...

What I did wrong ? Thx for anyHelp

**Comment by Imangazaliev** [comment]
This content is generated by JavaScript, so you can't get it when you load the page by PHP. Please google how to parse dymanically generated HTML
