### ISSUE TITLE
Utf-8 символы в методе html();

### ISSUE THREAD

**Issue by nullproduction** [Imangazaliev/DiDOM#14]
Вызываю метод html() и получаю вместо кириллицы utf-8 символы вида 

```
&#1058;&#1080;&#1084; &#1050;&#1091;&#1082;
```
Как конвертировать их к нормальному тексту? Ну и хотелось бы чтобы html() это делал по дефолту. 

На стековерфлоу нашел рекоммендацию указывать после загрузки \DOMDocument, не сработало.

```
$this->document->loadHtml($html);
$this->document->encoding = 'utf-8';
```

**Comment by Imangazaliev** [comment]
Можете привести пример кода?

**Comment by nullproduction** [comment]
@Imangazaliev да конечно. Чтобы увидеть что символы в utf, нужно будет исходный код страницы. Иначе браузер их выведет нормально
```
    /**
     * Test
     */
    public function test()
    {
        $url = 'http://appleinsider.ru/konkurs/vyigraj-bilet-na-koncert-frontmena-the-killers-ot-hp-i-appleinsider-ru.html';
        $document = new \DiDom\Document(file_get_contents($url));
        $element = $document->find('div.post-body')[0];
        echo $element->html();
    }
```

**Comment by nullproduction** [comment]
И исправил это ошибку и отправил pullrequest. Парсинг документов c кодировкой отличной от utf проверил, все работает

**Comment by nullproduction** [comment]
А чтобы последний коммит обновился чечез композер что нужно сделать?

**Comment by Imangazaliev** [comment]
Обновиться до 1.4.2

**Comment by nullproduction** [comment]
@Imangazaliev Есть еще одно приложение по поводу метода html(). Сейчас в тексте который выводит метод html вместо символа переноса строки "\r" выводится html сущность "&#13;" . Может имеет смысл сразу из преобразовывать? Консистентности данного блока вроде это не нурушает.

```php
   /**
     * Dumps the internal document into a string using HTML formatting.
     * 
     * @return string
     */
    public function html()
    {
        return trim(html_entity_decode($this->document->saveXML($this->getElement())));
    }
```
