### ISSUE TITLE
getting libxml error

### ISSUE THREAD

**Issue by msherax** [Imangazaliev/DiDOM#141]
I am getting this error when try to parse HTML.

`$dom = new Document();
$dom->loadHTML($htmlString);`

this is the error i get when loadHTML() is called.
> ErrorException
Use of undefined constant LIBXML_HTML_NOIMPLIED - assumed 'LIBXML_HTML_NOIMPLIED' (this will throw an Error in a future version of PHP)

can you guide me please about it?

**Comment by Imangazaliev** [comment]
Please google it
