### ISSUE TITLE
DiDOM удаляет <?=

### ISSUE THREAD

**Issue by RobertGard** [Imangazaliev/DiDOM#143]
Приветствую!
Загружаю содержимое php файла (в нём находится html и php вставки) через метод:   
`$document->loadHtml($html, LIBXML_HTML_NOIMPLIED | LIBXML_HTML_NODEFDTD);`
И всё бы хорошо, но если в коде находится  `<?=` , то `<?` удаляется и остаётся только `=`.
К примеру в коде файла есть вставка php <?= $demo; ?>, после того как я загружаю содержимое файла через метод `loadHtml` и вывожу с помощью метода `html()`, то мне отображается код вот с такой вставкой: `= $demo; ?>`.
Как это можно обойти ? 
Спасибо большое за библиотеку !

**Comment by RobertGard** [comment]
Плиз, подскажите кто-нибудь (

**Comment by Imangazaliev** [comment]
Лучше вырезать подобное регулярками перед созданием документа.
