### ISSUE TITLE
Как избавиться от оборачивания тегом <p> текста, который не обёрнут ни одним тегом? 

### ISSUE THREAD

**Issue by RobertGard** [Imangazaliev/DiDOM#144]
С помощью `$document->loadHtml($html, LIBXML_HTML_NOIMPLIED | LIBXML_HTML_NODEFDTD);` подгрузил HTML. В этом html есть текст, который не обёрнут тегами. 
Как пример: `<header></header>Вот тут текст<div></div>` 
 После вывода `$document->html()`, у того  текста, что ранее не был обёрнут появляется обертка тегом `<p>`. Как сделать так, что бы текст в таком случае не оборачивался тегом `<p>` ?

**Comment by Imangazaliev** [comment]
У XML или HTML элемента должен быть один корневой элемент, здесь же что-то не так. Если корневого элемента нет, нужно добавить его самому перед созданием документа, иначе результат может быть неожиданным (для вас). Если у нужного текстового узла нет класса или ID, по которому его можно получить, можно воспользоваться методами `previousSibling()` и `nextSibling()`.

**Comment by RobertGard** [comment]
Я извиняюсь, не смог ответить сразу на ваш ответ. 
@Imangazaliev Нет, мне не нужно получить этот текстовой узел. Мне нужно что бы этот текст, который не имел ранее обёртки, не оборачивался ни чем при создании документа.
На самом деле я немного упростил вопрос (избавился от не нужных деталей). Сейчас постараюсь его расписать подробнее, что объяснить свою проблему.

У меня в файле находится вот такой код (HTML и вставки PHP):
`<header>Вот тут текст шапки</header>
<?php foreach($array as $key => $item): ?>
  <?php echo $item;?>
<?php endforeach; ?>
<footer>Вот тут текст футера<footer>
`
После я передаю этот HTML вместе с PHP объекту класса Document с помощью метода loadHtml : `$document->loadHtml($html, LIBXML_HTML_NOIMPLIED | LIBXML_HTML_NODEFDTD);`

После этого я произвожу поиск в содержимом `<footer>` (предположим что там есть какая-то вложенность тегов, в примере я это намеренно опустил, но это на самом деле не важно, так как поиск происходит отлично). Далее я произвожу изменения в `<footer>`, что так происходит успешно. То есть нет проблем с поиском узлов и заменой их содержимого.  
Далее я вывожу тот код, что был в файлике (HTML и PHP) с помощью функции `$document->html()` .
И вот что мне выводит: 

`<header>Вот тут текст шапки</header>
<?php foreach($array as $key =><p> $item): ?>
</p>
  <?php echo $item;?>
<?php endforeach; ?>
<footer>Вот тут текст футера<footer>
`
То есть вставляется не нужная обёртка тегом `<p>`.

Даже если не производить поиск с помощью метода `find()` и не делать никаких изменений в HTML (что я указывал в примере) с помощью метода 'setValue()', а просто передать тот код что я указывал выше объекту  `$document` класса `Document` и вывести с помощью метода `html()`, то всё равно появится не нужная обёртка `<p>`. А мне нужно, что бы код можно было вернуть в том же виде, что я и передаю. 
Я надеюсь что смог объяснить свою проблему, для меня это важная задача, так как на принципе поиска в файлах (в которых есть и HTML и PHP) построен весь мой плагин.

**Comment by Imangazaliev** [comment]
@RobertGard это особенность расширения DOM PHP (ext-xml), который используется под капотом DiDOM. Попробуйте обернуть весь HTML в один тег, а потом получить его внутреннее содержимое, используя метод `innerHtml()`.

**Comment by RobertGard** [comment]
@Imangazaliev Хм, а это возможно будет решением. Спасибо, сегодня проверю
