### ISSUE TITLE
Не работает библиотека. Вообще

### ISSUE THREAD

**Issue by XTeslaUA** [Imangazaliev/DiDOM#145]
Здравствуйте. Извините за вопрос, но уже вторые сутки бьюсь и **ничего вообще не выводит и ошибок не говорит.** Все глухо и немо. И сразу вопрос, а зачем аж семь(!) файлов в одной простой и быстрой библиотеке? Просьба помочь. Может что лишнее подключил или не подключил, в документации для простых смертных хостингов про  с require_once без Composerов нет ни слова, люди какой-то vendor/apload.php подключают, но в исходниках его нет.

```
<?php
error_reporting(E_ALL);

require_once($_SERVER['DOCUMENT_ROOT'].'/DiDom/ClassAttribute.php');
require_once($_SERVER['DOCUMENT_ROOT'].'/DiDom/Document.php');
require_once($_SERVER['DOCUMENT_ROOT'].'/DiDom/Element.php');
require_once($_SERVER['DOCUMENT_ROOT'].'/DiDom/Encoder.php');
require_once($_SERVER['DOCUMENT_ROOT'].'/DiDom/Errors.php');
require_once($_SERVER['DOCUMENT_ROOT'].'/DiDom/Query.php');
require_once($_SERVER['DOCUMENT_ROOT'].'/DiDom/StyleAttribute.php');
require_once($_SERVER['DOCUMENT_ROOT'].'/DiDom/Exceptions/InvalidSelectorException.php');


use DiDom\ClassAttribute;
use DiDom\Document;
use DiDom\Element;
use DiDom\Encoder;
use DiDom\Errors;
use DiDom\Query;
use DiDom\StyleAttribute;
use DiDom\Exceptions\InvalidSelectorException;


$url = "https://torgi.gov.ru/lotSearchReport.html?showRelocatedLots=false&hasProtocols=false&agregateByNotification=false&LOT_NUMBER_CAST_LOT_NUMBER_AS_NUMBER=lotNumber,+cast(lotNumber+as+int)&onlySmps=false&propertyTypes_0=29&hasEtp=false&noCanceled=false&hasViolations=false&hasChanges=false&fullTextSearch=false&bidStatusId=2&LONG_LIST_excludeBidStatuses=1&notifDeleted=true&kladrIdStr=93644&isArchived=false&country_country=185&bindContextSearchResult=false&findAll=false&findForAllNotifFields=false&bidKindId=13&bidKindId=13&hasImages=false";


//создание документа
$document = new Document($url, true);
echo var_dump($document);
//вывод
echo $document;

?>
```

**Comment by XTeslaUA** [comment]
<?php
error_reporting(E_ALL);

require_once($_SERVER['DOCUMENT_ROOT'].'/DiDom/ClassAttribute.php');
require_once($_SERVER['DOCUMENT_ROOT'].'/DiDom/Document.php');
require_once($_SERVER['DOCUMENT_ROOT'].'/DiDom/Element.php');
require_once($_SERVER['DOCUMENT_ROOT'].'/DiDom/Encoder.php');
require_once($_SERVER['DOCUMENT_ROOT'].'/DiDom/Errors.php');
require_once($_SERVER['DOCUMENT_ROOT'].'/DiDom/Query.php');
require_once($_SERVER['DOCUMENT_ROOT'].'/DiDom/StyleAttribute.php');
require_once($_SERVER['DOCUMENT_ROOT'].'/DiDom/Exceptions/InvalidSelectorException.php');


use DiDom\ClassAttribute;
use DiDom\Document;
use DiDom\Element;
use DiDom\Encoder;
use DiDom\Errors;
use DiDom\Query;
use DiDom\StyleAttribute;
use DiDom\Exceptions\InvalidSelectorException;


$url = "https://torgi.gov.ru/lotSearchReport.html?showRelocatedLots=false&hasProtocols=false&agregateByNotification=false&LOT_NUMBER_CAST_LOT_NUMBER_AS_NUMBER=lotNumber,+cast(lotNumber+as+int)&onlySmps=false&propertyTypes_0=29&hasEtp=false&noCanceled=false&hasViolations=false&hasChanges=false&fullTextSearch=false&bidStatusId=2&LONG_LIST_excludeBidStatuses=1&notifDeleted=true&kladrIdStr=93644&isArchived=false&country_country=185&bindContextSearchResult=false&findAll=false&findForAllNotifFields=false&bidKindId=13&bidKindId=13&hasImages=false";


//создание документа
$document = new Document($url, true);
echo var_dump($document);
//вывод
echo $document;

?>

**Comment by XTeslaUA** [comment]
`
<?php
error_reporting(E_ALL);

require_once($_SERVER['DOCUMENT_ROOT'].'/DiDom/ClassAttribute.php');
require_once($_SERVER['DOCUMENT_ROOT'].'/DiDom/Document.php');
require_once($_SERVER['DOCUMENT_ROOT'].'/DiDom/Element.php');
require_once($_SERVER['DOCUMENT_ROOT'].'/DiDom/Encoder.php');
require_once($_SERVER['DOCUMENT_ROOT'].'/DiDom/Errors.php');
require_once($_SERVER['DOCUMENT_ROOT'].'/DiDom/Query.php');
require_once($_SERVER['DOCUMENT_ROOT'].'/DiDom/StyleAttribute.php');
require_once($_SERVER['DOCUMENT_ROOT'].'/DiDom/Exceptions/InvalidSelectorException.php');


use DiDom\ClassAttribute;
use DiDom\Document;
use DiDom\Element;
use DiDom\Encoder;
use DiDom\Errors;
use DiDom\Query;
use DiDom\StyleAttribute;
use DiDom\Exceptions\InvalidSelectorException;


$url = "https://torgi.gov.ru/lotSearchReport.html?showRelocatedLots=false&hasProtocols=false&agregateByNotification=false&LOT_NUMBER_CAST_LOT_NUMBER_AS_NUMBER=lotNumber,+cast(lotNumber+as+int)&onlySmps=false&propertyTypes_0=29&hasEtp=false&noCanceled=false&hasViolations=false&hasChanges=false&fullTextSearch=false&bidStatusId=2&LONG_LIST_excludeBidStatuses=1&notifDeleted=true&kladrIdStr=93644&isArchived=false&country_country=185&bindContextSearchResult=false&findAll=false&findForAllNotifFields=false&bidKindId=13&bidKindId=13&hasImages=false";


//создание документа
$document = new Document($url, true);
echo var_dump($document);
//вывод
echo $document;


?>
`

**Comment by Imangazaliev** [comment]
> вторые сутки бьюсь и ничего вообще не выводит и ошибок не говорит

Помимо `error_reporting(E_ALL);` нужно добавить `ini_set('display_errors', 1);`. 

> И сразу вопрос, а зачем аж семь(!) файлов в одной простой и быстрой библиотеке

Это не так много на самом деле. Видимо, вы ты новичок, поэтому тебе это непривычно.

> люди какой-то vendor/apload.php подключают

Точнее `vendor/autoload.php`. Это автолоадер Composer.

Советую узнать, что такое автолоадер, Composer и в целом подтянуться в PHP.
