### ISSUE TITLE
Invalid expression for query path

### ISSUE THREAD

**Issue by kowach** [Imangazaliev/DiDOM#151]
This query can return false into `$nodeList` and than foreach loop generates warning/error:

https://github.com/Imangazaliev/DiDOM/blob/00497fa519fe17c3349d922e6db7d43103e135a6/src/DiDom/Document.php#L443-L455

Invalid selector which generates error is `'[some_attribute = "some_value"]'` (notice spaces)

**Comment by Imangazaliev** [comment]
Perphaps I'll fix it in the future but I think it's not a serious issue.
