### ISSUE TITLE
Function parseStyleAttribute() in class StyleAttribute

### ISSUE THREAD

**Issue by edojdikov** [Imangazaliev/DiDOM#160]
Incorrect handling properties of the kind of
`image-background: url(https://domain.com)`
In the explode function to separate a property from a value, you must set a limit of up to 2 elements:
`list($name, $value) = explode(':', $property, 2);`

**Comment by Imangazaliev** [comment]
Fixed in [1.16.3](https://github.com/Imangazaliev/DiDOM/releases/tag/1.16.3). Thanks for feedback.
