### ISSUE TITLE
Some HTML Comments go on new line

### ISSUE THREAD

**Issue by miro-ux** [Imangazaliev/DiDOM#164]
When running this basic example:
```
$document = new Document('example.html', true);
echo $document;
```

I get the the following output:
![2021-03-02_022201](https://user-images.githubusercontent.com/7188826/109612974-86654e00-7afe-11eb-9042-d41c34294a01.jpg)

All comments following div, li, etc. (`<div/><div> <!--comment-->`) are on a new line. Notice that comment after `</header>` doesn't go on new line. 

_Edit: Just figured the ones that don't go on a new line is because there's already a new line right after the comment or element._

Here's the original `example.html`
![2021-03-02_022317](https://user-images.githubusercontent.com/7188826/109613158-c62c3580-7afe-11eb-8ee0-84102d86d32d.jpg)

**Comment by Imangazaliev** [comment]
Actually I can't control formatting because under the hood I just use PHP DOM extension. I can suggest only one solution:

```php
echo $document->format()->html()
```

If it's not working try to find an HMTL/XML formatting (beautifier) library.
