### ISSUE TITLE
Замена найденного элемента на HTML строку

### ISSUE THREAD

**Issue by FrozenCoyote** [Imangazaliev/DiDOM#165]
Подскажите, как заменить найденный элемент на некую HTML строку? Строка может быть весьма масштабна по сути, нет возможности переконвертировать ее в узлы через new Element. Есть ли какой либо способ произвести замены элемента на html строку, примерно по аналогии с replaceWith?

`                       
$embeds = $txt->find(".embed");
$replace = '<div><span>12345</span></div>';
foreach($embeds as $e)
{
$e->replace($replace); // ошибка
}
`

**Comment by cmkcmykmailru** [comment]
```PHP
        $embeds = $txt->find(".embed");
        $compDoc = new Document();
            $compDoc->load('<div><span>12345</span></div>',
                false, Document::TYPE_HTML, LIBXML_HTML_NOIMPLIED | LIBXML_HTML_NODEFDTD);
       
        foreach ($embeds as $e) {
            $newElement = $compDoc->toElement();
            $e->replace($newElement);
        }
                
```

**Comment by FrozenCoyote** [comment]
> ```
>         $embeds = $txt->find(".embed");
>         $newDoc = new Document();
>             $newDoc->load('<div><span>12345</span></div>',
>                 false, Document::TYPE_HTML, LIBXML_HTML_NOIMPLIED | LIBXML_HTML_NODEFDTD);
>        
>         foreach ($embeds as $e) {
>             $newElement = $newDoc->toElement();
>             $e->replace($newElement);
>         }
>                 
> ```
> 
> Как то так можно. Ну и учитывать, что вот так `$newDoc->load('<div><span>12345</span></div><div><span>12345</span></div>', false, Document::TYPE_HTML, LIBXML_HTML_NOIMPLIED | LIBXML_HTML_NODEFDTD);` без рутового тега у вас потеряется часть, т.е. лучше оборачивать во что-то, например `'<wrapfragment><div><span>12345</span></div><div><span>12345</span></div></wrapfragment>'`

спасибо!
