### ISSUE TITLE
Проблема с кодировкой

### ISSUE THREAD

**Issue by ooPASHAoo** [Imangazaliev/DiDOM#17]
Пробовал в различных вариациях, такой вариант мне кажется самым наглядным.
Суть в том что слетают русские буквы при utf-8 

<img width="880" alt="2015-11-25 16 58 12" src="https://cloud.githubusercontent.com/assets/12009088/11399172/9e112b64-9396-11e5-8c50-21178790a602.png">

        $text = 'текст text текст text';

        dd(mb_detect_encoding($text));            // UTF-8
        dd($text);                                // "текст text текст text"

        $document = new Document($text);

        dd(mb_detect_encoding($document->html()));// UTF-8
        dd($document->html());                    // "<html><body><p>Ñ‚ÐµÐºÑÑ‚ text Ñ‚ÐµÐºÑÑ‚ text</p></body></html>"

**Comment by Imangazaliev** [comment]
Причина и решение найдены. Будет исправлено в следующем релизе

**Comment by ooPASHAoo** [comment]
Большое спасибо, работает!
Теги для поиска: utf-8, coding, encoding, кодировка, русские буквы, Ñ, кириллица, ->html()
