### ISSUE TITLE
closest parent Element

### ISSUE THREAD

**Issue by yehia1ali** [Imangazaliev/DiDOM#175]
i've some tags like:

 
![image](https://user-images.githubusercontent.com/42983220/136299955-1ca4c281-3ffc-437d-84a0-64a60d77b1b4.png)

How do I shorten that without using parent twice
something like 
https://developer.mozilla.org/en-US/docs/Web/API/Element/closest

**Comment by Imangazaliev** [comment]
DiDOM Element has `closest()` method:

```
$ancestor = $document->first('h1')->closest('.my-class');
```
