### ISSUE TITLE
file_get_contents(url): failed to open stream: HTTP request failed! HTTP/1.1 403 Forbidden in .../vendor/imangazaliev/didom/src/DiDom/Document.php on line 391

### ISSUE THREAD

**Issue by whvlsd** [Imangazaliev/DiDOM#176]
Использую Вашу библиотеку для парсинга уже давно и впервые встретился с подобной проблемой. Запускали на хостинге - file_get_contents(url): failed to open stream: HTTP request failed! HTTP/1.1 403 Forbidden, запустили на локалке - работает замечательно. Пробовали использовать прокси - не помогают
С чем может быть связано?

**Comment by KarelWintersky** [comment]
`allow_url_fopen` в PHP.INI должно быть установлено значение `on`

Проверьте наличие расширения ` php_openssl`

**Comment by Imangazaliev** [comment]
Возможность загрузки файлов в DiDom сделана для удобства работы в простых случаях, для более гибкой работы нужно использовать cURL, либо обертки типа Guzzle. Похожие issue: #1, #37, #52, #66, #112.
