### ISSUE TITLE
А можно ли брать текст без <html><body>...</html></body>?

### ISSUE THREAD

**Issue by ooPASHAoo** [Imangazaliev/DiDOM#18]
Было бы здорово взять текст из объекта без этих тегов, так как далеко не всегда парсят страницы, в моем случае я редактирую статью.
Какой нибудь $document->html(true) 
 Если такая возможность есть, то извиняюсь.

**Comment by Imangazaliev** [comment]
@ooPASHAoo , есть:
```php
$document->text();
```

**Comment by ooPASHAoo** [comment]
Эта штука вырезает все теги. То есть p и img и прочие. А хотелось бы, что бы можно было взять часть сайта, отредактировать и сохранить

**Comment by ooPASHAoo** [comment]
я новичок, у меня сейчас вот так
<img width="354" alt="2015-11-25 22 27 19" src="https://cloud.githubusercontent.com/assets/12009088/11407410/b7e5676c-93c3-11e5-90c5-54effe7809d8.png">

**Comment by Imangazaliev** [comment]
#27

**Comment by Imangazaliev** [comment]
#27 Решение проблемы
