### ISSUE TITLE
Поиск елементов по дата атрибутам

### ISSUE THREAD

**Issue by LogansUA** [Imangazaliev/DiDOM#19]
Здравствуйте.
* **Во-первых** хочу сказать, что эта либа действительно отличная вещь и вы проделали отличную работу;
* **Во-вторых**, есть ли возможность вытягивать елемент по дата атрибуту?

Пример, ссылка с дата атрибутом:
```html
<a href="#hello" data-element="qwerty">
    <div>Some text</div>
</a>
```
Сейчас я делаю так:
```php
$html = <<<HTML
<a href="#hello" data-element="qwerty">
    <div>Some text</div>
</a>
HTML;

$document = new Document($html);
$links    = $document->find("[data-element='qwerty']");
```
Получаю пустой массив.

Благодарю.

**Comment by Imangazaliev** [comment]
Здравствуйте. Какую версию DiDom вы используете? Возможно вы используете неправильный селектор. Если версия меньше 1.5 значение атрибута должно быть указано без кавычек.

**Comment by LogansUA** [comment]
@Imangazaliev благодарю, работает шикарно :)
