### ISSUE TITLE
PHP 8.2 deprecated mb_convert_encoding.

### ISSUE THREAD

**Issue by TalantRys** [Imangazaliev/DiDOM#194]
I coded my website in PHP 7.2 and uploaded it to Railway.app for test. It turned out, Railway.app uses the latest version 8.2, which is why an error appeared:

Deprecated: mb_convert_encoding(): Handling HTML entities via mbstring is deprecated; use htmlspecialchars, htmlentities, or mb_encode_numericentity/mb_decode_numericentity instead in /app/libs/imangazaliev/didom/src/DiDom/Encoder.php on line 18

Can i change mb_convert_encoding by myself and be sure it's not gonna give another error?

**Comment by barchard** [comment]
As a temporary workaround, I suppressed this on my load/create call like:

```
@Document::create($html);
```

**Comment by Imangazaliev** [comment]
Fixed in [2.0.1](https://github.com/Imangazaliev/DiDOM/releases/tag/2.0.1).
