### ISSUE TITLE
Странный текст

### ISSUE THREAD

**Issue by uonick** [Imangazaliev/DiDOM#2]
> В качестве выражения для можно передать CSS-селектор

в ридми :+1:

**Comment by slaFFik** [comment]
This is a blocking issue, I suppose

**Comment by Imangazaliev** [comment]
Спасибо за замечание, исправлено

**Comment by slaFFik** [comment]
https://github.com/Imangazaliev/DiDOM/commit/2e6910fa14c6e9d49a3b8408f23a6579335359a8
