### ISSUE TITLE
Вопрос по оптимизации

### ISSUE THREAD

**Issue by takoe** [Imangazaliev/DiDOM#21]
Добрый день.

Использую библиотеку впервые, но она уже произвела хорошее впечатление.

Интересует такой момент по оптимизации:
Влияет ли на скорость работы использование "контекста" для поиска?
Например, получаем большую страницу ``` $document = new Document($link, true);``` Далее нам нужно собрать массив из элементов этой страницы:
```php
$el["name"] = $document->find('.element-name')[0]->getAttribute('name');
$el["value"] = $document->find('.element-value')[0]->text();
```
и т.д. 

Все поиски ведутся через переменную $document. Будет ли какая-то разница в скорости работы, если использовать контекст? Например,
```php
$document = new Document($link, true);
$section = $document->find('.elements-list');

$el["name"] = $section[0]->find('.element-name')[0]->getAttribute('name');
$el["value"] = $section[0]->find('.element-value')[0]->text();
```
Или это только добавляет лишний запрос?

**Comment by Imangazaliev** [comment]
Да, разница есть. Во втором случае преобразование CSS-селектора в XPath-выражение и поиск элементов происходят три раза, в первом - только два. Кстати, если вы вам нужно получить несколько атрибутов какого-либо элемента, будет лучше предварительно сохранить его в переменную, чтобы не выполнять поиск несколько раз. В вашем случае можно сделать так:

```php
$el["name"] = $section[0]->find('.elements-list .element-name')[0]->getAttribute('name');
$el["value"] = $section[0]->find('.elements-list .element-value')[0]->text();
```
