### ISSUE TITLE
Не могу запустить скрипт

### ISSUE THREAD

**Issue by shlyahten** [Imangazaliev/DiDOM#24]
Не получается запустить скрипт. Брал код из примера, сервер ругается на отсутствие класса. Может это очень глупый вопрос, но как использовать скрипт без composer? Пытался инклудить файлы - не помогло. Помогите, пожалуйста.

**Comment by Imangazaliev** [comment]
Все должно работать. Подключаете все файлы и дописываете:
`
use DiDom\Document;
`

**Comment by shlyahten** [comment]
@Imangazaliev подключать через include_once?

**Comment by Imangazaliev** [comment]
@shlyahten, как угодно. Я бы сделал через require. А еще лучше изучить Composer.
