### ISSUE TITLE
Incorrectly parsing <i> tag when placed within <a> tags

### ISSUE THREAD

**Issue by outboundexplorer** [Imangazaliev/DiDOM#26]
I've come across this problem where my `<i>` tags are not being parsed correctly, I discovered, that the tag is becoming incomplete when passed through DOM construction.

I have found that when i place an `<i>` tag within `<a>` tags, the `<i>` tag is losing the closing tag.

`$body = '<a href="#"><i class="fa fa-globe"></i></a>';`
 `$document = new Document($body);`
 `\Log::info((string) $document);`

This will become:

`'<html><body><a href="#"><i class="fa fa-globe"/></a></body></html>'`

I also tried the following and they seemed to be OK.

`'<p>He named his car <i>The lightning</i>, because it was very fast.</p>'`
`'<a href="#"><span>Hello</span></a>'`

Really nice DOM package. :)

**Comment by Muhammad97** [comment]
Thank you for your feedback. I know about it, in the next release this will be fixed.

**Comment by Imangazaliev** [comment]
Thank you for your feedback. I know about it, in the next release this will be fixed.

**Comment by outboundexplorer** [comment]
Brilliant.  I'll keep my eye open for the next release.  Any ideas when it might be ready?

**Comment by Imangazaliev** [comment]
Two or three days.

**Comment by outboundexplorer** [comment]
Brilliant. Thanks.

**Comment by Imangazaliev** [comment]
[Released](https://github.com/Imangazaliev/DiDOM/releases/tag/1.6.1). Update to 1.6.1

**Comment by outboundexplorer** [comment]
Tested this morning.  At first I triggered an error because I didn't realize that `$document->html(LIBXML_NOEMPTYTAG);` would stop being a `Document` object.

I simply changed my code around and made sure that I used this line of code after performing all my other actions on the $document.

All good and working nicely :)
