### ISSUE TITLE
Как подключить?

### ISSUE THREAD

**Issue by my-instantcms** [Imangazaliev/DiDOM#28]
Здравствуйте, извините за тупой вопрос, но как подключить парсер к своему файлу?
Разработка идет на денвере, но не знаю какой файл include-ом подключить к себе?

**Comment by Imangazaliev** [comment]
Для установки библиотеки воспользуйтесь [Composer](https://getcomposer.org/)'ом.

**Comment by my-instantcms** [comment]
без Composer-а никак? в денвере нет возможности воспользоваться Composer'ом. :(

**Comment by Imangazaliev** [comment]
Еще как есть. Composer'у без разницы с чем работать, да и денверу тоже.
