### ISSUE TITLE
HTML fragment is automatically wrapped with <p>

### ISSUE THREAD

**Issue by brusch** [Imangazaliev/DiDOM#31]
This is similar to #27 but affects HTML fragments which do not have a wrapped element. 

### Example: 

        $content = "This is just a <b>short</b> test!";

        $document = new \DiDom\Document();
        $document->loadHtml($content, LIBXML_HTML_NOIMPLIED | LIBXML_BIGLINES | LIBXML_HTML_NODEFDTD | LIBXML_PARSEHUGE);

        echo $document->html();

### Expected result
```This is just a <b>short</b> test!```

### Current result
```<p>This is just a <b>short</b> test!</p>```

**Comment by Imangazaliev** [comment]
```php
$content = "This is just a <b>short</b> test!";

$document = new \DiDom\Document();
$document->loadHtml($content, LIBXML_HTML_NOIMPLIED | LIBXML_BIGLINES | LIBXML_HTML_NODEFDTD | LIBXML_PARSEHUGE);

echo $document->toElement()->innerHtml();
```

## Output
```
This is just a <b>short</b> test!
```

**Comment by brusch** [comment]
Hmmm, but I think this should be detected automatically, not? 
Otherwise you have to do some manual checks before, followed by some IFs to handle all the different types of inputs :(

**Comment by Imangazaliev** [comment]
Perhaps then it is better to wrap all of the elements ? The div, e.g.

**Comment by brusch** [comment]
Sure, that would be the best approach, but the problem is that I want to integrate DiDom into https://github.com/pimcore/pimcore where the developers can create their own templates, so there's no way to ensure a wrapping elements at the top level nor is it always wanted.:(
So an automated handling would be just perfect (as simple_html_dom does).

**Comment by Imangazaliev** [comment]
@brusch:
## Example 1
```php
$html = 'This is just a <b>short</b> test!';

// wrap elements in a div
$html = sprintf('<div>%s</div>', $html);

$document = new \DiDom\Document();
$document->loadHtml($html, LIBXML_HTML_NOIMPLIED | LIBXML_BIGLINES | LIBXML_HTML_NODEFDTD | LIBXML_PARSEHUGE);

echo $document->toElement()->innerHtml();
```

## Output
```html
This is just a <b>short</b> test!
```
## Example 2
```php
$html = 'This is just a <b>short</b> test!';

// wrap elements in a div
$html = sprintf('<div>%s</div>', $html);

$document = new \DiDom\Document();
$document->loadHtml($html, LIBXML_HTML_NOIMPLIED | LIBXML_BIGLINES | LIBXML_HTML_NODEFDTD | LIBXML_PARSEHUGE);

echo $document->toElement()->innerHtml();
```

## Output
```html
<div>Lorem ipsum <span>dolor</span> sit amet.</div>
```
