### ISSUE TITLE
HTML fragment with multiple root nodes

### ISSUE THREAD

**Issue by brusch** [Imangazaliev/DiDOM#32]
### Example

        $content = "<div>This is just a <b>short</b> test!</div><div>Another Test</div>";

        $document = new \DiDom\Document();
        $document->loadHtml($content, LIBXML_HTML_NOIMPLIED | LIBXML_BIGLINES | LIBXML_HTML_NODEFDTD | LIBXML_PARSEHUGE);

        echo $document->html();

### Expected result
```<div>This is just a <b>short</b> test!</div><div>Another Test</div>```
## Current result
```<div>This is just a <b>short</b> test!</div>```

**Comment by Imangazaliev** [comment]
Try to wrap it in another element and then call innerHtml:
```php
$content = "<div><div>This is just a <b>short</b> test!</div><div>Another Test</div></div>";

$document = new \DiDom\Document();
$document->loadHtml($content, LIBXML_HTML_NOIMPLIED | LIBXML_BIGLINES | LIBXML_HTML_NODEFDTD | LIBXML_PARSEHUGE);

echo $document->toElement()->innerHtml();
```
## Output:
```
<div>This is just a <b>short</b> test!</div><div>Another Test</div>
```

**Comment by brusch** [comment]
see also #31
