### ISSUE TITLE
Can't set attribute in loop

### ISSUE THREAD

**Issue by DarkPreacher** [Imangazaliev/DiDOM#34]
Code example:
```php
$html = new Document($file_name, true);
foreach ( $html->find($selector)[0]->find('img') as $element ) {
    $element->src = self::embed($path);
}
```
Expected: `<img src="'data:image/jpg;base64,base64_encode_output" />`
Got old src attr value.

**Comment by Imangazaliev** [comment]
Try to combine selectors ($selector+'img').
## Example
#### source.html
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
</head>
<body>
    <ul class="menu">
        <li><a href="http://google.com" title="Link 1">Link 1</a></li>
        <li><a href="http://google.com" title="Link 2">Link 2</a></li>
        <li><a href="http://google.com" title="Link 3">Link 3</a></li>
    </ul>
</body>
</html>
```
### Your code

```php
$filename = 'source.html';

$document = new \DiDom\Document($filename, true);

foreach ( $document->find('ul')[0]->find('li a') as $element ) {
    $element->href = 'http://example.com';
}

echo $document->html();
```

Nothing changed.

### With combined selectors

```php
$filename = 'source.html';

$document = new \DiDom\Document($filename, true);

foreach ( $document->find('ul li a') as $element ) {
    $element->href = 'http://example.com';
}

echo $document->html();
```

The links has changed to `example.com`.

**Comment by DarkPreacher** [comment]
Yep, works like a charm, thank you!
But I've got another problem, with greed. For example I have something like `&lt;img src="image.png"&gt;` in `<pre>` and parser counts that as img, so in output it's converted to `<img src="image.png">` — is there something I can do about this?

**Comment by Imangazaliev** [comment]
I have no such problem.
## source.html
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
</head>
<body>
    <h1>Test</h1>
    <pre>
        &lt;img src="image.png"&gt;
    </pre>
</body>
</html>
```
## index.php
```php
$document = new \DiDom\Document('source.html', true);

echo $document->format()->html();
```
## Output
![image](https://cloud.githubusercontent.com/assets/11244193/14454615/1ec7a010-00a4-11e6-903f-6ed4d3455894.png)

**Comment by Imangazaliev** [comment]
Please, check: http://stackoverflow.com/questions/2142120/php-encoding-with-domdocument

**Comment by DarkPreacher** [comment]
Nope, there is something wrong on my side I guess. I copied your example, created file with utf-8 encoding, tested and still got converted entities. Also tryed `$string = mb_convert_encoding($string, 'html-entities', 'utf-8');` without any luck.

**Comment by DarkPreacher** [comment]
I'm using `->innerHtml()`, which returns `html_entity_decode`, that's why I'm getting this problem.

**Comment by Imangazaliev** [comment]
Fixed. Please, update to [1.6.6](https://github.com/Imangazaliev/DiDOM/releases/tag/1.6.6)

**Comment by DarkPreacher** [comment]
Yep, works like a charm, thank you!
