### ISSUE TITLE
Encoding issue

### ISSUE THREAD

**Issue by Andrewkha** [Imangazaliev/DiDOM#36]
HI

I'm using your lib to parse some HTML pages. When the task is run as crontab job, everything is OK. But once I try to parse the same page via interactive action in browser, it parses the source page in wrong encoding. Any recommendations to fix it? Attaching an example of print_r of some piece of parsed page
![capture](https://cloud.githubusercontent.com/assets/9628186/14755470/2b69fef4-08eb-11e6-80c8-a87a562b6efc.PNG)

**Comment by Imangazaliev** [comment]
Hello. Can you show your code?

**Comment by Andrewkha** [comment]
Thanks for quick response. The code is very simple. Before providing it, some more observations:

1. Unix based production environment, script executed via crontab - no issues
2. Windows development environment, script executed via command line or Web Intergace - no issues
3. Unix based production environment, scrip executed via Web Interface on Windows machine - encoding issues.

In all cases the actual parsing function is the same, just called different ways

I use Yii 2. So now the code, nothing specific, very straight forward
`$url = $this->autoProcessURL; // I parse pages on sports.ru, for example http://www.sports.ru/bundesliga/calendar/
        $html = new Document($url, true);
        $count = $this->num_tours;
        $j = 0;
        $gamesFromWeb = [];
        for($i = 0; $i < $count; $i++) {
            $tour = $html->find('h3.titleH3')[$i]->text();
            $resultTable = $html->find('table.stat-table')[$i];`

**Comment by Andrewkha** [comment]
Hello!

sorry for the follow up. Do you have any ideas about such behavior?

**Comment by Imangazaliev** [comment]
1. Save file in UTF-8 encoding without BOM
2. Set encoding of document via [meta encoding tag](http://www.w3schools.com/tags/att_meta_charset.asp)

**Comment by Andrewkha** [comment]
Thanks for response, but all my project files are exactly in UTF-8 and I definitely have the correct meta tag. One more interesting observation. I used PHP Simple HTML DOM library for parsing, it worked with no issues. Later I found your lib and it works MUCH faster. So I didn't change anything related to encoding, just replaced one lib with another
![meta](https://cloud.githubusercontent.com/assets/9628186/15145705/d438a1d4-16bf-11e6-873a-1836d485f6e3.PNG)

![utf](https://cloud.githubusercontent.com/assets/9628186/15145636/76280ecc-16bf-11e6-8db8-fcc03941d40e.PNG)

**Comment by Imangazaliev** [comment]
Then it is necessary to look at the encoding of the document , which you parse. If encoding of document is not UTF- 8, you can use the [mb_convert_encoding](http://php.net/manual/ru/function.mb-convert-encoding.php).

**Comment by Andrewkha** [comment]
Well, here's what I see in the header
![capture](https://cloud.githubusercontent.com/assets/9628186/15146083/03662f56-16c2-11e6-9bff-4384f061349e.PNG)

**Comment by keremcankaya0** [comment]
Any updates on the issue? By the way it's super fast, great job

**Comment by Imangazaliev** [comment]
@keremcankaya0 are you faced a similar problem? Can you create a new issue?
