### ISSUE TITLE
Ошибка при попытке заменить элемент ( $post->replace() )

### ISSUE THREAD

**Issue by sunhaim** [Imangazaliev/DiDOM#42]
При попытке замены элемента выводит ошибку 

> Argument 1 passed to DOMNode::isSameNode() must be an instance of DOMNode, null given, called in /...../vendor/imangazaliev/didom/src/DiDom/Element.php on line 339 and defined

```
$document = new Document( 'https://habrahabr.ru/', true );
$posts = $document->find( '.post' );
foreach ( $posts as $post ) {
    $post->replace( new Element( 'span', 'Working', [ 'class' => 'alert alert-success' ] ) );
}
```

**Comment by Imangazaliev** [comment]
Исправлено в новой версии [1.6.8](https://github.com/Imangazaliev/DiDOM/releases/tag/1.6.8)
