### ISSUE TITLE
Missing pseudo class "nth-of-type"

### ISSUE THREAD

**Issue by tobeorla** [Imangazaliev/DiDOM#45]
¡Thank you for making this awesome library!

**Ref**: http://www.w3schools.com/cssref/sel_nth-of-type.asp
**Location**: https://github.com/Imangazaliev/DiDOM/blob/master/src/DiDom/Query.php#L251

**Example**

**php**
```php
<?php

require 'vendor/autoload.php';

$content = new \DiDom\Document("HTML_CODE");
$content->find("ul:nth-of-type(2) li"); // should return an array of "second list" lis
```

**HTML:**
```html
<html>
<head>
</head>
<body>
    <ul>
        <li>first list</li>
        <li>first list</li>
        <li>first list</li>
        <li>first list</li>
    </ul>
    <ul>
        <li>second list</li>
        <li>second list</li>
        <li>second list</li>
        <li>second list</li>
    </ul>
</body>
</html>
```

I would add it myself, but i don't understand the other pseudo classes code.
Hope this helps you to make it possible :p

**Comment by Imangazaliev** [comment]
Thank you for your feedback..

**Comment by Imangazaliev** [comment]
Update to [1.7.2](https://github.com/Imangazaliev/DiDOM/releases/tag/1.7.2)
