### ISSUE TITLE
Catchable fatal error

### ISSUE THREAD

**Issue by Grafs** [Imangazaliev/DiDOM#46]
$item = $document->find('ul.menu > li')[1];
// предыдущий элемент
var_dump($item->previousSibling());
Catchable fatal error: Argument 1 passed to DiDom\Element::setNode() must be an instance of DOMElement, instance of DOMText given, called in \vendor\imangazaliev\didom\src\DiDom\Element.php on line 32 and defined in \vendor\imangazaliev\didom\src\DiDom\Element.php on line 452

**Comment by Imangazaliev** [comment]
Спасибо за отзыв, подумаю над решением

**Comment by Grafs** [comment]
Те же проблемы и с 
// string(3) "Baz"
var_dump($item->child(2)->text());

// string(3) "Foo"
var_dump($item->firstChild()->text());

// string(3) "Baz"
var_dump($item->lastChild()->text());

// array(3) { ... }
var_dump($item->children());

Если можно, можете быстрее подумать? 
Ваша бибилиотека супер, не хочется менять

**Comment by Imangazaliev** [comment]
Исправлено в [1.7.4](https://github.com/Imangazaliev/DiDOM/releases/tag/1.7.4)

**Comment by Grafs** [comment]
Problem 1
    - The requested package imangazaliev/didom >=1.7.4 is satisfiable by imangaz
aliev/didom[dev-master] but these conflict with your requirements or minimum-sta
bility.

**Comment by Grafs** [comment]
В версии 1.7.4 все равно не верно работает парсер, проверьте:
```
$doc = new Document('https://themeforest.net/category/wordpress', true);
$res=$doc->find('.meta-categories b');
foreach ( $res as $item ) {
echo '<br><b>previousSibling:</b><br>'.highlight_string(print_r($item->previousSibling()->text(), true), true).'<br>';
echo '<br><b>lastChild:</b><br>'.highlight_string(print_r($item->lastChild()->text(), true), true).'<br>';
}
```

**Comment by Imangazaliev** [comment]
А что именно не так работает?

**Comment by Grafs** [comment]
Там ведь в примере все видно. 
HTML
```
<span class="meta-categories -no-slash">
   in 
    <b>WordPress</b> /
    <b>Corporate</b> /
  <b itemprop="genre">Business</b>
</span>
```
$item->lastChild()->text() должен вывести **Business** а выводит **WordPress** и т.д.

$item->previousSibling()->text() вообще выводит **in** 

Проверьте сами, я ведь код выше дал

**Comment by Imangazaliev** [comment]
Просто ты неправильно задал селектор. На этот раз проблема не в парсере. Для отладки можно использовать консоль разработчика в браузере и `document.querySelectorAll`
![image](https://cloud.githubusercontent.com/assets/11244193/18248488/29fd13a2-7381-11e6-9241-e0fa17b1c5a6.png)

**Comment by Grafs** [comment]
Даже если так, то $item->lastChild()->text() должен вывести WooCommerce а выводит WordPress. Почему?
