### ISSUE TITLE
Ничего не возвращают lastChild() nextSibling() и previousSibling() 

### ISSUE THREAD

**Issue by Grafs** [Imangazaliev/DiDOM#47]
Вот ваш пример:

```php
$html = '
<ul>
    <li>Foo</li>
    <li>Bar</li>
    <li>Baz</li>
</ul>
';
$document = new Document($html);
$list = $document->first('ul');
// string(3) "Baz"
echo '<br><b>$list->child(2)->text():</b><br>'.highlight_string(print_r($list->child(2)->text(), true), true).'<br>';
// string(3) "Foo"
echo '<br><b>$list->firstChild()->text():</b><br>'.highlight_string(print_r($list->firstChild()->text(), true), true).'<br>';
// string(3) "Baz" - нет ничего
echo '<br><b>$list->lastChild()->text():</b><br>'.highlight_string(print_r($list->lastChild()->text(), true), true).'<br>';

$document = new Document($html);
$item = $document->find('ul > li')[1];
echo '<br><b>$item->previousSibling():</b><br>'.highlight_string(print_r($item->previousSibling()->text(), true), true).'<br>';
echo '<br><b>$item->nextSibling():</b><br>'.highlight_string(print_r($item->nextSibling()->text(), true), true).'<br>';
```
$list->lastChild()->text() ничего не возвращает
nextSibling() и previousSibling() так же ничего

**Comment by Imangazaliev** [comment]
Все верно. Здесь учитываются и пробелы и переносы строк. Еще еще и текстовые узлы. Посмотри свойство preserveWhiteSpace: http://php.net/manual/ru/class.domdocument.php.

```php
$document->getDocument()->preserveWhiteSpace = false;
```

**Comment by Grafs** [comment]
> Здесь учитываются и пробелы и переносы строк.
Хм, странно. Какие пробелы и переносы строк если я выбираю только ul > li
У вас написано, должен ->lastChild() возвратить  string(3) "Baz" но ничего не возвращает. Это у вас ошибка в документации?
При этом child(2) и firstChild() отрабатывает верно.
По вашей логике "Здесь учитываются и пробелы и переносы строк" что то из этого работает не верно.

**Comment by Imangazaliev** [comment]
Вот такой код, в одну строку:

```php
$html = '<ul><li>Foo</li><li>Bar</li><li>Baz</li></ul>';
```

А насчет доки - спасибо за замечание, посмотрю.

**Comment by Imangazaliev** [comment]
Нашел статью на эту тему: http://msyk.es/blog/domdocument-whitespace-php. Только там регулярка неправильная, должно быть:

```php
$html = preg_replace("/>\s+</", "><", $html);
```

**Comment by Imangazaliev** [comment]
Нашел еще одно решение:

```php
$html = '
<ul>
    <li>Foo</li>
    <li>Bar</li>
    <li>Baz</li>
</ul>
';

$document = new Document();

// не учитываем пробелы и переносы строк
$document->getDocument()->preserveWhiteSpace = false;

// важно использовать именно loadXml
// т.к. для loadHtml preserveWhiteSpace  не работает
$document->loadXml($html);

// string(3) "Baz"
var_dump($document->find('ul')[0]->lastChild()->text());
```

**Comment by Grafs** [comment]
Я это решил с помощью xpath
```
$document = new Document($html);
$item = $document->xpath('//ul');

$item2 = $document->xpath('//li[1]');
echo '<br><b>First:</b><br>'.highlight_string(print_r($item2[0]->text(), true), true).'<br>';
	
$item2 = $document->xpath('//li[2]');
echo '<br><b>Child(1):</b><br>'.highlight_string(print_r($item2[0]->text(), true), true).'<br>';
	
$item2 = $document->xpath('//li[last()]');
echo '<br><b>Last:</b><br>'.highlight_string(print_r($item2[0]->text(), true), true).'<br>';
	
$item2 = $document->xpath('//li[2]/preceding-sibling::*[1]');
echo '<br><b>Prev1 from Bar:</b><br>'.highlight_string(print_r($item2[0]->text(), true), true).'<br>';
	
$item2 = $document->xpath('//li[2]/following-sibling::*[1]');
echo '<br><b>Next1 from Bar:</b><br>'.highlight_string(print_r($item2[0]->text(), true), true).'<br>';
```
Но это обход бага 
Ваши ->lastChild() ->previousSibling() ->nextSibling() не работают, это баг в модуле.

**Comment by Imangazaliev** [comment]
> Про $document->getDocument()->preserveWhiteSpace = false; у вас в документации нигде не сказано

Просто не встречался с подобным до этого. Не все примеры из доки проверял, есть такой косяк.

> Как то с этими методами не все нативно получилочь в вашем модуле.

Этот момент не очень понял. В следующей версии будет метод preserveWhiteSpace, ин шаа Ллах.

> Может сделать по умолчанию в консрукторе предобработчик регуляркой для $html?
> Либо доп метод типа

Нужно подумать. Возможно не всем это нужно и не всегда полезно (например, тег pre)

> И еще у вас не поддерживается псевдокласс :nth-last-child

В следующей версии.

**Comment by Grafs** [comment]
Ок, спасибо большое за ответы. Жду новую версию

**Comment by Imangazaliev** [comment]
Вышел релиз [1.8](https://github.com/Imangazaliev/DiDOM/releases/tag/1.8). Поддержку селектора `:nth-last-child` решил не добавлять, т.к. это потребовало бы довольно серьезных изменений, а соответственно и падение скорости, при том что этот псевдокласс используется не так часто. Однако это можно реализовать с помощью XPath, пример можно посмотреть [здесь](https://en.wikibooks.org/w/index.php?title=XPath/CSS_Equivalents).
