### ISSUE TITLE
Не работает метод remove.

### ISSUE THREAD

**Issue by mezhevikin** [Imangazaliev/DiDOM#48]
Добрый день. Видел issue с этой проблемой ( https://github.com/Imangazaliev/DiDOM/issues/39 ), но вы ее закрыли не дождавшись от автора примера кода.

Сделал специальный упрощенный пример:

```
   $content = '<html><div id="c">text text text <div id="e">div</div> test test</div></html>';
    $document = new Document($content);
    $div = $document->first('div#c');
    $div->first('div#e')->remove();
    dd($div->html());
```

Вывод:

`<div id="c">text text text <div id="e">div</div> test test</div>`

То есть див с идентификатором e остался на месте после вызова remove.

**Comment by Imangazaliev** [comment]
Ну, все верно. Удалить можно только те элементы, которые были найдены непосредственно в документе. Пример:

```php
// ничего не выйдет
$document->first('#c')->first('#e')->remove();

// а вот так да
$document->first('#c #e')->remove();
```

Причину можно понять, если посмотреть исходный код метода find класса Element. Там создается новый документ (временный), никак не связанный с первоначальным документом.

**Comment by Imangazaliev** [comment]
Хорошо, дополню этот раздел, ин шаа Ллах. Спасибо за фидбек

**Comment by mezhevikin** [comment]
@Imangazaliev спасибо за библиотеку 👍👆
