### ISSUE TITLE
<script> ломает xpath парсер

### ISSUE THREAD

**Issue by tasgard** [Imangazaliev/DiDOM#49]
Приветствую! По какой то причине данный код:
```html
<td id="main_col">
    <div class="borderwrap">
        <script type="text/javascript">
        new Array(
            "~~NODIV~~<div>BREAKME</div>",
        )
        </script>
        <a href="http://test.com">TEST</a>
    </div>
</td>
```
ломает xpath парсер с выражением:
`//td[@id="main_col"]/div[@class="borderwrap"]//a/@href`

Попробуйте убрать строку `"~~NODIV~~<div>BREAKME</div>",` и мы получаем то что нужно.

**Comment by tasgard** [comment]
рабочий костыль: `preg_replace("!<script[^>]*>(.)*</script>!Uis", null, $html)` паттерн нашел на просторах...

**Comment by Imangazaliev** [comment]
Все верно, эта штука "запутывает парсер". И дело здесь не в DiDom,  а в расширении dom, т.к. именно он отвечает за парсинг:

```php
$document = new Document($html);

var_dump($document->format()->html());
```

Результат:

```html
<html>
  <body>
    <td id="main_col">&#13;
    <div class="borderwrap">&#13;
        <script type="text/javascript"><![CDATA[
        new Array(
            "~~NODIV~~<div>BREAKME]]></script></div>",&#13;
        )&#13;
        &#13;
        <a href="http://test.com">TEST</a>&#13;
    &#13;
</td>
  </body>
</html>
```

Так что вариант с регуляркой вполне нормальный. Кстати, вместо XPath можно использовать следующий CSS-селектор: `td#main_col div.borderwrap a::attr(href)`

**Comment by tasgard** [comment]
получается нужно общаться уже с разработчиками расширения?

**Comment by Imangazaliev** [comment]
Вряд ли ваше сообщение что-то решит, но попытаться можно. Я бы все таки воспользовался регуляркой перед созданием документа.
