### ISSUE TITLE
Css2Xpath не работоспособен

### ISSUE THREAD

**Issue by coollider** [Imangazaliev/DiDOM#5]
`#my-id[attr0="attr-value0"][attr1='attr-value1']`

конвертируем в xPath, результат

`*[@id='my-id[attr0="attr-value0"][attr1="attr-value1"]']`

**Comment by Imangazaliev** [comment]
Исправлено в релизе 1.3. Использовать нужно так:
```css
 #my-id[attr0=attr-value0][attr1=attr-value1] 
```
т.е. без кавычек
