### ISSUE TITLE
Out of memory

### ISSUE THREAD

**Issue by WillColl** [Imangazaliev/DiDOM#50]
А что делать, если есть XML Файл размером 500+ Mb, в котором больше 5миллионов строк?

**Comment by WillColl** [comment]
Тут или использовать потоки (я пробовал SAX всякие, свой писал на потоках, xml-string-streamer использовал), но время выполнения таких скриптов переваливает за 10 минут что нам не позволительно, или давать вашему плагину дофига оперативки. Но с последним, что-то не удачно, даже всякие ACPu или OPCache мне не особо помогли. Какие выходы из подобной ситуации видите вы?

**Comment by WillColl** [comment]
Вопрос решил чистым SQL
XML пример
`<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ICECAT-interface SYSTEM "http://data.icecat.biz/dtd/files.index.dtd">


<ICECAT-interface xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://data.icecat.biz/xsd/files.index.xsd">
  <files.index Generated="20160924012000">
  <file path="export/freexml.int/NL/1467.xml" Product_ID="1467" Updated="20160923111419" Quality="ICECAT" Supplier_id="1" Prod_ID="Q1428A" Catid="847" On_Market="1" Model_Name="Universal High-gloss Photo Paper" Product_View="133406" HighPic="http://images.icecat.biz/img/norm/high/1467-6015.jpg" HighPicSize="22221" HighPicWidth="400" HighPicHeight="400" Date_Added="20050902000000">
    <EAN_UPCS>
      <EAN_UPC Value="0725184660405"/>
      <EAN_UPC Value="0725184536731"/>
      <EAN_UPC Value="0848412013740"/>
      <EAN_UPC Value="7251846604058"/>
      <EAN_UPC Value="7330381004902"/>
      <EAN_UPC Value="0848412014402"/>
    </EAN_UPCS>
    <Country_Markets>
      <Country_Market Value="DE"/>
      <Country_Market Value="GB"/>
      <Country_Market Value="NL"/>
      <Country_Market Value="MX"/>
      <Country_Market Value="US"/>
    </Country_Markets>
  </file>
  <file path="export/freexml.int/NL/1694.xml" Product_ID="1694" Updated="20160923142016" Quality="ICECAT" Supplier_id="1" Prod_ID="C4823A" Catid="846" On_Market="1" Model_Name="C4823A" Product_View="207199" HighPic="http://images.icecat.biz/img/norm/high/1694-HP.jpg" HighPicSize="28612" HighPicWidth="400" HighPicHeight="400" Date_Added="20051027000000">
    <EAN_UPCS>
      <EAN_UPC Value="0886985416544"/>
      <EAN_UPC Value="0807027516879"/>
      <EAN_UPC Value="5051395329516"/>
      <EAN_UPC Value="5052461548046"/>
      <EAN_UPC Value="5052916433750"/>
      <EAN_UPC Value="4053162277014"/>
      <EAN_UPC Value="0088698541654"/>
    </EAN_UPCS>
    <Country_Markets>
      <Country_Market Value="AT"/>
      <Country_Market Value="PL"/>
      <Country_Market Value="DE"/>
      <Country_Market Value="CH"/>
      <Country_Market Value="FR"/>
      <Country_Market Value="NL"/>
      <Country_Market Value="GB"/>
      <Country_Market Value="DK"/>
      <Country_Market Value="BE"/>
      <Country_Market Value="ES"/>
      <Country_Market Value="MX"/>
      <Country_Market Value="IT"/>
      <Country_Market Value="SE"/>
      <Country_Market Value="US"/>
      <Country_Market Value="RU"/>
      <Country_Market Value="TR"/>
      <Country_Market Value="HU"/>
      <Country_Market Value="FI"/>
      <Country_Market Value="PT"/>
      <Country_Market Value="NO"/>
    </Country_Markets>
  </file>
  <file path="export/freexml.int/NL/1698.xml" Product_ID="1698" Updated="20160923135305" Quality="ICECAT" Supplier_id="1" Prod_ID="C4941A" Catid="377" On_Market="1" Model_Name="C4941A" Product_View="179291" HighPic="http://images.icecat.biz/img/norm/high/1698-HP.jpg" HighPicSize="25281" HighPicWidth="400" HighPicHeight="400" Date_Added="20051028000000">
    <EAN_UPCS>
      <EAN_UPC Value="5704327420279"/>
      <EAN_UPC Value="0025184251758"/>
      <EAN_UPC Value="5051964024361"/>
      <EAN_UPC Value="4053162277335"/>
      <EAN_UPC Value="0251842527556"/>
      <EAN_UPC Value="0025184252755"/>
    </EAN_UPCS>
    <Country_Markets>
      <Country_Market Value="DK"/>
      <Country_Market Value="FR"/>
      <Country_Market Value="AT"/>
      <Country_Market Value="DE"/>
      <Country_Market Value="PL"/>
      <Country_Market Value="CH"/>
      <Country_Market Value="NL"/>
      <Country_Market Value="GB"/>
      <Country_Market Value="BE"/>
      <Country_Market Value="ES"/>
      <Country_Market Value="MX"/>
      <Country_Market Value="IT"/>
      <Country_Market Value="SE"/>
      <Country_Market Value="US"/>
      <Country_Market Value="HU"/>
      <Country_Market Value="FI"/>
      <Country_Market Value="PT"/>
      <Country_Market Value="NO"/>
    </Country_Markets>
  </file>
  <file path="export/freexml.int/NL/1719.xml" Product_ID="1719" Updated="20160923160407" Quality="ICECAT" Supplier_id="1" Prod_ID="C6570C" Catid="971" On_Market="1" Model_Name="C6570C" Product_View="112368" HighPic="http://images.icecat.biz/img/norm/high/1719-HP.jpg" HighPicSize="22006" HighPicWidth="400" HighPicHeight="400" Date_Added="20050728000000">
    <M_Prod_ID Supplier_id="10219" Supplier_name="BMG Ariola">C6570C</M_Prod_ID>
    <EAN_UPCS>
      <EAN_UPC Value="0251841968510"/>
      <EAN_UPC Value="5051749582215"/>
      <EAN_UPC Value="4053162279339"/>
      <EAN_UPC Value="0848412013146"/>
      <EAN_UPC Value="0025184196851"/>
    </EAN_UPCS>
    <Country_Markets>
      <Country_Market Value="DE"/>
      <Country_Market Value="GB"/>
      <Country_Market Value="NL"/>
      <Country_Market Value="DK"/>
      <Country_Market Value="IT"/>
      <Country_Market Value="SE"/>
      <Country_Market Value="US"/>
      <Country_Market Value="NO"/>
    </Country_Markets>
  </file>
</files.index>
</ICECAT-interface>`

SQL запрос
`LOAD XML LOCAL INFILE '$filePath' INTO TABLE icecatindex ROWS IDENTIFIED BY '<file>' 
(@Product_ID, @Quality , @Supplier_id ,
	@Prod_ID , @Catid , @On_Market , @Model_Name , 
	@HighPic ,@path ,@Updated, @Product_View, 
	@HighPicSize, @HighPicWidth ,@HighPicHeight, @Date_Added) 
SET Product_ID = @Product_ID, Quality = @Quality, 
	Supplier_id = @Supplier_id, Prod_ID = @Prod_ID, 
	Catid = @Catid, On_Market = @On_Market, Model_Name = @Model_Name, 
	HighPic = @HighPic, path = @path, Updated = @Updated, 
	Product_View = @Product_View, HighPicSize = @HighPicSize, 
	HighPicWidth = @HighPicWidth, HighPicHeight = @HighPicHeight,Date_Added = @Date_Added;`

**Comment by Imangazaliev** [comment]
Сам спросил, сам решил ) а что за это файл такой боьшой?

**Comment by WillColl** [comment]
[Icecat](http://icecat.de/)
Единый каталог техники.
Сейчас пытаюсь максимально ускорить запрос в базу
```sql
ALTER TABLE icecatindex DISABLE KEYS;
LOCK TABLES icecatindex WRITE;
SET AUTOCOMMIT = 0;
SET FOREIGN_KEY_CHECKS = 0; 
SET UNIQUE_CHECKS = 0;
SET SQL_LOG_BIN = 0;
LOAD XML LOCAL INFILE '$filePath' 
    INTO TABLE icecatindex 
    ROWS IDENTIFIED BY '<file>' ;

SET FOREIGN_KEY_CHECKS=1;
SET UNIQUE_CHECKS=1;
COMMIT;
UNLOCK TABLES;
ALTER TABLE icecatindex ENABLE KEYS;
```

+ увеличение буфера mysql
+ использование MyISAM
