### ISSUE TITLE
Is there a way to modify innertext/text ?

### ISSUE THREAD

**Issue by smurfiez** [Imangazaliev/DiDOM#51]
I've tried modify->text and text() but they both don't work

**Comment by smurfiez** [comment]
`	foreach ($document->find('div.category') as $a) {

		$a->setInnerHtml  = '';
           // var_dump($a);
	}`


I've tried that too and it still outputs the original content

**Comment by Imangazaliev** [comment]
Yes, you can use `setInnerHtml` method:

```php
$element->setInnerHtml($html);
```

**Comment by smurfiez** [comment]
Oh, yeah I figured that out. it doesn't work when there's a second find though, is there anyway around that?  Thanks for the reply

**Comment by smurfiez** [comment]
I actually meant say we have $a->find('span')[0]->find('em')[0]->setInnerHtml

**Comment by Imangazaliev** [comment]
From https://github.com/Imangazaliev/DiDOM/issues/48:

> Well, all right. You can remove only those elements which were found in the directly in document. Example:
> 
> ```php
> // will not work
> $document->first('#c')->first('#e')->remove();
> 
> // you can do like this
> $document->first('#c #e')->remove();
> ```
> 
> The reason can be understood if we look at the source code of the method find Element class. It creates a new document (temporary), unrelated to the original document.

**Comment by smurfiez** [comment]
Ah thank you very much, I ended up replacing the old element with the new element since the items inside the first element may change
