### ISSUE TITLE
php_network_getaddresses: getaddrinfo failed: Name or service not known !!

### ISSUE THREAD

**Issue by atefBB** [Imangazaliev/DiDOM#52]
Hi, I'm using DiDom with laravel 4.2, and when I try to analyse a website to get the HTML I got this error:
`file_get_contents(): php_network_getaddresses: getaddrinfo failed: Name or service not known' in /home/atef/public_html/seomara/vendor/imangazaliev/didom/src/DiDom/Document.php:252`.
Can you help me?!

**Comment by Imangazaliev** [comment]
Hello. Please see #1, #37 and #30.

**Comment by atefBB** [comment]
Thanks !! 
But how could I use this with Guzzle ?!! should I send a request with Guzzle and send the result to  DiDom object?
Is that possible in such case !?

**Comment by Imangazaliev** [comment]
Yes

**Comment by atefBB** [comment]
Thaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaak you !
