### ISSUE TITLE
About $dom->first() return null

### ISSUE THREAD

**Issue by li7721994** [Imangazaliev/DiDOM#53]
Hi guy
When I want to get the text of element which is not exist in the html
(Just like this:`$dom->first('#productCode')->text()`) ,
 it will show the `Fata Error` in the PHP Engine 
because `$dom->first('#productCode')` => `return null`.

Can we use `$dom->first('#productCode')->text()` without showing Error in the future, like`$('#someSelector').find('#productCode').text()` on [Jquery](http://jquery.com),

**Comment by Imangazaliev** [comment]
Hello. You can do like this:

```php
$text = $dom->has('#productCode') ? $dom->first('#productCode')->text() : null;
```

Or this:

```php
$node = $dom->first('#productCode');

$text = $node === null ? null : $node->text();
```

**Comment by li7721994** [comment]
thx~
