### ISSUE TITLE
Class 'DiDom\Errors' not found

### ISSUE THREAD

**Issue by graid2030** [Imangazaliev/DiDOM#54]
Hello!
After update from "imangazaliev/didom (1.7.3)" to "imangazaliev/didom (1.8.3)"

Class 'DiDom\Errors' not found

in .../vendor/imangazaliev/didom/src/DiDom/Document.php:162

**Comment by Imangazaliev** [comment]
Hi. Are you use Composer? Try run `composer dump-autoload`
