### ISSUE TITLE
Multiple URL's

### ISSUE THREAD

**Issue by JakeHenshall** [Imangazaliev/DiDOM#57]
Hey,]

Really nice script I've been messing around with it for abit,

But I just can't figure out how to accomplish this.

I'm trying to loop through multiple url's but cannot seem to achieve this.

        $names = ['a', 'b', 'c', 'd'];

        foreach ($names as $name) {
            $name = $name;
        }

        $document = new Document('http://www.website.com/link/' . $name, true);

        $posts = $document->find('.classname');

        foreach($posts as $post) {
            echo $post->text(), "\n";
        }

This only seems to display d

But what I would like it to do is go to all 4 links and bring back the copy from those

http://www.website.com/link/a
- Copy from A

http://www.website.com/link/b
- Copy from B

http://www.website.com/link/c
- Copy from C

http://www.website.com/link/d
- Copy from D

all on the same page.

**Comment by Imangazaliev** [comment]
```php
$names = ['a', 'b', 'c', 'd'];

foreach ($names as $name) {
    $name = $name;

    $document = new Document('http://www.website.com/link/' . $name, true);

    $posts = $document->find('.classname');

    foreach($posts as $post) {
        echo $post->text(), "\n";
    }
}
```
