### ISSUE TITLE
Memory Usage

### ISSUE THREAD

**Issue by smurfiez** [Imangazaliev/DiDOM#58]
What is the best way to optimize memory usage for this class.  Is there a way to unset all variables used in the class in case I'm using this in a long running script? 

Or would just an unset($didom) do the trick.  Once again, thank you for creating such an awesome class.

**Comment by Imangazaliev** [comment]
Hello. I have not thought about it because the library and so consumes little memory.

**Comment by smurfiez** [comment]
Oh, I use this library quite extensively for scraping since its quite easy to use and efficient.   I notice memory builds up after scraping  a few million pages though :(
