### ISSUE TITLE
Attribute selector

### ISSUE THREAD

**Issue by smurfiez** [Imangazaliev/DiDOM#59]
`
DiDom\Element Object
(
    [node:protected] => DOMElement Object
        (
            [tagName] => img
            [schemaTypeInfo] => 
            [nodeName] => img
            [nodeValue] => 
            [nodeType] => 1
            [parentNode] => (object value omitted)
            [childNodes] => (object value omitted)
            [firstChild] => 
            [lastChild] => 
            [previousSibling] => (object value omitted)
            [nextSibling] => (object value omitted)
            [attributes] => (object value omitted)
            [ownerDocument] => (object value omitted)
            [namespaceURI] => 
            [prefix] => 
            [localName] => img
            [baseURI] => 
            [textContent] => 
        )

)
<br />
<b>Fatal error</b>:  Call to a member function attr() on null in <b>/d/functions.php</b> on line <b>66</b><br />`

Any idea why I can't use the attr function, if I use ->src it works fine but I need to get a

**Comment by smurfiez** [comment]
The element is there, just wonder why it comes null

**Comment by smurfiez** [comment]
`        $document = $this->document;
        if (count($elements = $document->find('article.grid-col--fixed-tiles')) != 0) {
            foreach ($elements as $k => $e) {
                $ret = [];
                $ret['href'] = $e->find('a')[0]->attr('href');`

Code looks a bit like that.  If i use ->href it works but not if I use the attr or getAtttribute

**Comment by Imangazaliev** [comment]
```php
ini_set('display_errors', true);
ini_set('error_reporing', E_ALL);

// your code here
```

It means that tag `a` not found in element. *Note:* you can use `first` method instead of `find(...)[0]`
