### ISSUE TITLE
Multiple Elements

### ISSUE THREAD

**Issue by JakeHenshall** [Imangazaliev/DiDOM#61]
Hi,

I looking to try and pull down images in SVG and also other elements from the page and loop through them. How do i go about this?

    $names = ['a', 'b', 'c', 'd'];

    foreach ($names as $name) {
        $name = $name;
    }

    $document = new Document('http://www.website.com/link/' . $name, true);

    $posts = $document->find('.classname');
    // $title = $document->find('.title'); ????????
    // Does it need to go here e.g $icon = $document->find('img[src$=svg]');

    foreach($posts as $post) {
        echo $post->text(), "\n";
        // How do i loop through the images & titles?
    }

Any help is much appreciated.

Thanks Jake.

**Comment by Imangazaliev** [comment]
Hello.

```php
foreach ($names as $name) {
    $name = $name;
}
```

What its doing?

```php
$names = ['a', 'b', 'c', 'd'];

foreach ($names as $name) {
    $document = new Document('http://www.website.com/link/' . $name, true);

    $posts = $document->find('.classname');
    // $title = $document->find('.title'); ????????
    // Does it need to go here e.g $icon = $document->find('img[src$=svg]');

    foreach($posts as $post) {
        echo $post->text(), "\n";
        // How do i loop through the images & titles?
    }
}
```

**Comment by JakeHenshall** [comment]
Hi,

Basically what i'm trying todo is get multiple elements from a domain.

I'm confused with.

1. How to Loop through and display multiple bits of data
2. How to get a certain image from the site 
3. How to Work with Caching 
4. How to save the results to a Database

Any examples for these would be great.

Thanks Jake.

**Comment by Imangazaliev** [comment]
All this does not belong to the parser, so I have to close this issue

**Comment by JakeHenshall** [comment]
@Imangazaliev how does this not? can you please show me an example of getting 2 separate elements from a webpage.

**Comment by Imangazaliev** [comment]
I can not understand what you want to do. If you want to get few elements with different selector you can do like this:

```php
$elements = $document->get('div.foo, img[src="bar"]');
```

**Comment by JakeHenshall** [comment]
@Imangazaliev Ok, how can i output those into the foreach loop?

**Comment by Imangazaliev** [comment]
```php
foreach ($elements as $element) {
    echo $element->html();
}
```

**Comment by JakeHenshall** [comment]
ok thanks, is there a way that I can do this

get the title, image and some description.

And use that data in a foreach loop?

**Comment by JakeHenshall** [comment]
@Imangazaliev Once they are in the foreach loop how can i just call out the title or the image?

Thanks Jake.

**Comment by Imangazaliev** [comment]
```php
echo $document->first('img')->text();

foreach ($document->find('img')) {
    echo $img->src, PHP_EOL;
}
```

**Comment by JakeHenshall** [comment]
@Imangazaliev Cheers man i'll have a look tonight and let you know I'm just trying to get my head around the script, thanks for all of the help so far and the quick responses much appreciated.
