### ISSUE TITLE
Bug: <img..> to <img..></img>

### ISSUE THREAD

**Issue by testnameforbug** [Imangazaliev/DiDOM#64]
Hello. In last version have bug:   it echo `<img..></img>`, but not `<img>`

```
$html = '<div class="block-media"><img src="image.png"></div>';
$doc = new Document();
$doc->loadHtml($html);
$data = $doc->xpath('//div');
print_r($data[0]->html());
```

old version is GOOD:
`<div class="block-media"><img src="image.png"/></div>`

NEW version is BAD:
`<div class="block-media"><img src="image.png"></img></div>`

**Comment by Imangazaliev** [comment]
Hello. It is not bug. In new version I pass LIBXML_NOEMPTYTAG ([Document](https://github.com/Imangazaliev/DiDOM/blob/master/src/DiDom/Document.php#L435), [Element](https://github.com/Imangazaliev/DiDOM/blob/master/src/DiDom/Element.php#L374)). You can do this:

```
$data[0]->html(0);
```
