### ISSUE TITLE
file_get_contents(https://.....com): failed to open stream !!

### ISSUE THREAD

**Issue by atefBB** [Imangazaliev/DiDOM#65]
Hey, I'm trying to parse this URL 'eloquentbyexample.com' and it's sucks with this exception:
`file_get_contents(https://eloquentbyexample.com): failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found ' in /..../vendor/imangazaliev/didom/src/DiDom/Document.php:252`.
Have an idea to solve this?
thx!

**Comment by atefBB** [comment]
Wa 'Alykom Assalem ! 
I got this UGLY page : 
![dfdf](https://cloud.githubusercontent.com/assets/10966925/20858987/400f367c-b952-11e6-8121-ce9e19598586.png)

**Comment by Imangazaliev** [comment]
Click to `Parametres Avances`

**Comment by atefBB** [comment]
You mean `Advanced Settings` ?!
I got this : 
![dfdf](https://cloud.githubusercontent.com/assets/10966925/20860512/4f5a7218-b97a-11e6-9ce8-50a44608ab04.png)

**Comment by atefBB** [comment]
I click `continue to thr website ... (danger)` (translation) and I got a `beautiful` 404 page error : 
![dfdf](https://cloud.githubusercontent.com/assets/10966925/20860525/9ae51440-b97a-11e6-87d3-a20f2d9f3969.png)

**Comment by Imangazaliev** [comment]
Yes

**Comment by atefBB** [comment]
what this can mean?!
how to solve this issue?

**Comment by Imangazaliev** [comment]
Its mean that page does not exists :) I dont know how to solve this problem

**Comment by atefBB** [comment]
The site exists  already : 
![lkflk](https://cloud.githubusercontent.com/assets/10966925/20865798/37ced524-ba1c-11e6-92ea-bf4e38a90f93.png)

Strange behaviour?!! isn't it?
Anyway thx for interesting!

**Comment by aziev** [comment]
@atefBB try to use http instead of https

**Comment by shulard** [comment]
Hello,

Try using `http` instead of `https` protocol, the website is accessible for me only at the URL : http://eloquentbyexample.com.

**Comment by atefBB** [comment]
hi @shulard the URL is accessible in `https` !
