### ISSUE TITLE
Does it support cookies?

### ISSUE THREAD

**Issue by deli6z** [Imangazaliev/DiDOM#66]
First of all thank you for a great tool.
Now, the question is whether it supports cookies? We parse some website which returns this page "Sorry, we just need to make sure you're not a robot. For best results, please make sure your browser is accepting cookies."
Is there a way to handle it?

Thank you

**Comment by Imangazaliev** [comment]
Hello. Please see here: #1, #37

**Comment by deli6z** [comment]
Thanks. That makes sense, will use Guzzle then
