### ISSUE TITLE
How to echo entire html?

### ISSUE THREAD

**Issue by testnameforbug** [Imangazaliev/DiDOM#67]
Good morning. This code
```
$html = '<div> </div> <div class="media"><img src="image.png"></div>';
$doc = new Document();
$doc->loadHtml($html, LIBXML_HTML_NOIMPLIED | LIBXML_HTML_NODEFDTD);
print_r( $doc->html(0) );
print_r( (string)$doc );
```
echo this:
`<div> </div><div> </div>`

but how I can echo entire html? 

and if I write this `print_r($doc->format()->html(0));` it echo only `<div> </div>`, but I need entire html code.

**Comment by Imangazaliev** [comment]
Hello. You trying to create document with multiple root. Just wrap it to another div. See also: #32
