### ISSUE TITLE
How to fix this in new didom version?

### ISSUE THREAD

**Issue by testnameforbug** [Imangazaliev/DiDOM#68]
I'm using didom for html. Please tell, how I can fix...

1. now I see on each line end this:
`&#13;`
how I can disable this?

2. all title="" and alt="" values converted to:
like this:
`title="&#x123;&#x456;&#x789;"`

3. how to disable convertation `<p></p>` to `<p/>`

--------------

code:
```
$doc = new Document();
$doc->loadHtml($html, LIBXML_HTML_NOIMPLIED | LIBXML_HTML_NODEFDTD | LIBXML_BIGLINES | LIBXML_PARSEHUGE);
...
echo $doc->toElement()->innerHtml(0);
```

**Comment by Imangazaliev** [comment]
Hello. What version of DiDom are you use?

1, 2. Try this:

```php
$html = $doc->toElement()->innerHtml(0);

echo html_entity_decode($html);
```

3. It is not possible. LIBXML_NOEMPTYTAG option passing by default and if you not pass options (`innerHtml(0)`) empty tags will be converted to single tag. Unfortunately, I'm don't know how to fix it.

**Comment by testnameforbug** [comment]
last didom version

**Comment by testnameforbug** [comment]
Here are the solution:

code for check it:```

$html = "<mydocroooot> $html </mydocroooot>";
$doc = new Document();
$doc->loadHtml($html, LIBXML_HTML_NOIMPLIED | LIBXML_HTML_NODEFDTD | LIBXML_BIGLINES | LIBXML_PARSEHUGE);
print_r($doc->toElement()->innerHtml(0));
```
IF `$html = '<div></div><p></p><div class="block-media"><img src="image.png"></div>';`
RESULT IS: `<div/><p/><div class="block-media"><img src="image.png"/></div>`

BUT IF `$html = '<div> </div><p> </p><div class="block-media"><img src="image.png"></div>';`
RESULT IS:  `<div> </div><p> </p><div class="block-media"><img src="image.png"/></div>`

So, solution is: `$html = mb_ereg_replace('></', '> </', $html);`
(performance = 1000 html --> 0.2 sec)
