### ISSUE TITLE
Кодировочка

### ISSUE THREAD

**Issue by devmru** [Imangazaliev/DiDOM#7]
Здравствуйте. У меня проблема. Всё делаю curl'ом. 
Сначала вывожу что мне вернула функция с curl'ом. С кодировкой проблем нет. Для примера привожу вывод части страницы
```
Нет комментариев
```
Теперь всё тоже самое, но объявляю объект класса `Document` и вывожу через метод `html()`. Для примера привожу вывод той же части страницы.
```
ÐÐµÑ ÐºÐ¾Ð¼Ð¼ÐµÐ½ÑÐ°ÑÐ¸ÐµÐ²
```

**Comment by devmru** [comment]
Нашёл решение.
Перед объявлением объекта
```php
mb_convert_encoding($html,'UTF-8')
```

**Comment by ooPASHAoo** [comment]
Не помогло =(

**Comment by Imangazaliev** [comment]
Исправлено в версии 1.5
