### ISSUE TITLE
 failed to open stream

### ISSUE THREAD

**Issue by atefBB** [Imangazaliev/DiDOM#71]
Assalam Alykom ! (Peace be Upon YOU)
I have this error while try to parse a site : 
`file_get_contents(https://site.com): failed to open stream: HTTP request failed! HTTP/1.1 500 Internal Server Error` .
The parsed website return `301 Moved Permanently`.
Any ideas?

**Comment by Imangazaliev** [comment]
Wa alaykum salam wa rahmatullah ahi. Please see here: #1, #37, #66. Can you show me URL of the site

**Comment by atefBB** [comment]
this error occurs with some sites like : novatis.tn and bison.tn.

**Comment by atefBB** [comment]
If I understand the issue, I must use a tool like Guzzle to download the 'parsed' site and send it to DiDom. Am I right?

**Comment by Imangazaliev** [comment]
Yes

**Comment by atefBB** [comment]
Thanks ! My prob was with Guzzle package not with DiDom package.
