### ISSUE TITLE
calling of javascript

### ISSUE THREAD

**Issue by bestboom** [Imangazaliev/DiDOM#75]
New to this DiDOM as I got a script and trying to get it working with your help
Have this 
`foreach ($document->find('div.ads3') as $a) {
    $a->setValue('');
}`
Looking to run adsense code for this dIV

`$scripty = ('<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client=""
     data-ad-slot=""
     data-ad-format="auto"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>');`

tried this 

`$a->setInnerHtml($scripty);`

It gets code instead of showing ads, can you help me to resolve as I am not good of handling DiDOM

**Comment by Imangazaliev** [comment]
Hello. PHP can not interpret the JavaScript-code.

**Comment by bestboom** [comment]
Any solution to solving Javascripts?

**Comment by Imangazaliev** [comment]
Yes, you can use NodeJS
