### ISSUE TITLE
I cant installed many times

### ISSUE THREAD

**Issue by rexa5512** [Imangazaliev/DiDOM#79]
I was try installed on my XAMPP but always error

  Problem 1
    - The requested package imangazaliev/didom No version set (parsed as 1.0.0)
is satisfiable by imangazaliev/didom[No version set (parsed as 1.0.0)] but these
 conflict with your requirements or minimum-stability.

Installation failed, reverting ./composer.json to its original content.

can you help me how to fix it ?

**Comment by Imangazaliev** [comment]
Please show me your composer.json

**Comment by rexa5512** [comment]
this is my composer.json

{
    "name": "imangazaliev/didom",
    "description": "Simple and fast HTML parser",
    "type": "library",
    "keywords": ["didom", "parser", "html", "xml"],
    "license": "MIT",
    "homepage": "https://github.com/Imangazaliev/DiDOM",
    "authors": [
        {
            "name": "Imangazaliev Muhammad",
            "email": "imangazalievm@gmail.com"
        }
    ],
    "require": {
        "php": ">=5.4"
    },
    "require-dev": {
        "phpunit/phpunit": "^4.8"
    },
    "autoload": {
        "psr-4": {
            "DiDom\\": "src/DiDom/"
        }
    },
    "autoload-dev": {
        "psr-4": { 
            "Tests\\": "tests/"
        }
    }
}

**Comment by Imangazaliev** [comment]
Remove composer.json and run this command:

```sh
composer require imangazaliev/didom
```

**Comment by rexa5512** [comment]
I see I was done installed this is report 
"C:\xampp\htdocs\didom>composer require imangazaliev/didom
Using version ^1.9 for imangazaliev/didom
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing imangazaliev/didom (1.9.1): Downloading (100%)
Writing lock file
Generating autoload files"

how to use it. I was try create index.php but always 

"Class 'DiDom\Document' not found"

can you help me with that ?

**Comment by Imangazaliev** [comment]
Do you included `vendor/autoload.php`?

**Comment by rexa5512** [comment]
awesome.
thanks for help me, now that work  :+1:
