### ISSUE TITLE
Last 5 days does not work - loadXmlFile

### ISSUE THREAD

**Issue by chelkaz** [Imangazaliev/DiDOM#83]
```
$document = new Document();
    $item = $document->loadXmlFile('https://news.yandex.com/world.rss');
```

- ErrorException in Document.php line 314:

- file_get_contents(): SSL operation failed with code 1. OpenSSL Error messages:

- error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed

**Comment by Imangazaliev** [comment]
Please see here: #1, #37, #66
