### ISSUE TITLE
Encoder problem

### ISSUE THREAD

**Issue by kowach** [Imangazaliev/DiDOM#85]
I've updated DiDom to version 1.10.* and some errors started to appear.
PHP Warning:  mb_convert_encoding(): Illegal character encoding specified in imangazaliev/didom/src/DiDom/Encoder.php on line 16

    return mb_convert_encoding($string, 'HTML-ENTITIES', $encoding);

So I dumped $encoding, in first iteration it was UTF-8, but all others it was NULL

I have code something lik this:

    $dom = new DiDom();
    $dom->loadHtml( $html1 ); // no error
    ... $dom->find() ...
    $dom->loadHtml( $html2 ); // encoding is null
    ....

both html1 and html2 are utf8 encoded strings, but with not header and charset definition.

**Comment by Imangazaliev** [comment]
Can you send me your code including HTML?

**Comment by kowach** [comment]
HTML is simple

    $dom = new \DiDom\Document();
    $dom->loadHtml( '<div><p>test1</p></div>' );
    $dom->loadHtml( '<div><p>test2</p></div>' ); 

Executed on PHP 7.0.19

	PHP Warning:  mb_convert_encoding(): Illegal character encoding specified in ./DiDom/Encoder.php on line 16
	PHP Stack trace:
	...
	3. DiDom\Document->load($string = '<div><p>test2</p></div>', $isFile = FALSE, $type = 'html', $options = 4) ./DiDom/Document.php:239
	4. DiDom\Encoder::convertToHtmlEntities($string = '<div><p>test2</p></div>', $encoding = NULL) ./DiDom/Document.php:214
	5. mb_convert_encoding('<div><p>test2</p></div>', 'HTML-ENTITIES', '') ./DiDom/Encoder.php:16

**Comment by Imangazaliev** [comment]
Fixed. Please update to [1.10.5](https://github.com/Imangazaliev/DiDOM/releases/tag/1.10.5)
