### ISSUE TITLE
hao can I get data from alibaba

### ISSUE THREAD

**Issue by vs412237401** [Imangazaliev/DiDOM#86]
hao can I get data from alibaba?
for example, when I want to get data from this page

https://detail.1688.com/offer/531594994445.html?spm=a262g1.8679128.j2k71xte.1.0IKX18

it failed, but when I use this code get data, it can work

`$ali1688_url = 'https://detail.1688.com/offer/555292199552.html?spm=a2604.8625596.j1lio959.21.OWwTCB';

$ch = curl_init();
curl_setopt($ch, CURLOPT_URL, $ali1688_url);
//curl_setopt($ch, CURLOPT_ENCODING, 'gbk');
curl_setopt($ch, CURLOPT_USERAGENT, 'Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36');
$result = curl_exec($ch);
$result=iconv('gb2312','utf-8',$result);
curl_close($ch);

print_r($result);`

**Comment by Imangazaliev** [comment]
Hello. Your code is not related to DiDOM. You can ask your question on forums (StackOverflow, for example) or programming chats
