### ISSUE TITLE
$item instead of $list in README.md

### ISSUE THREAD

**Issue by Heart1010** [Imangazaliev/DiDOM#87]
In the **[Getting the child elements](https://github.com/Imangazaliev/DiDOM/blob/master/README.md#getting-the-child-elements)** section of the README file you use `$item->...` in the var_dump() lines. Shouldn't this be `$list->...`?

**Comment by Imangazaliev** [comment]
Sure. I'll fix it, thank you

**Comment by Imangazaliev** [comment]
Fixed
