### ISSUE TITLE
Searching through an <table>

### ISSUE THREAD

**Issue by timo002** [Imangazaliev/DiDOM#88]
Hello,

I'm trying the traverse through a table. But I can't get this working. 

Below my test code:

```
<?php
require __DIR__."/vendor/autoload.php";
use DiDom\Document;

$html = "<table>
<tr>
<td>TR1:TD1</td>
<td>TR1:TD2</td>
<td>TR1:TD3</td>
<td>TR1:TD4</td>
</tr>
<tr>
<td>TR2:TD1</td>
<td>TR2:TD2</td>
<td>TR2:TD3</td>
<td>TR2:TD4</td>
</tr>
</table>";

$document = new Document($html);
$table = $document->find('table > tr');

# Walking through all rows
foreach($table as $index => $row){
    # now getting into the columns <td>
    var_dump($row->child(0)->text());
}
```
Output:
$ php test.php
test.php:29:
string(1) "
"
test.php:29:
string(1) "
"

How will I be able to go through this table by row and by column?

**Comment by Imangazaliev** [comment]
Hi. You should consider that the text is also considered a separate node (white spaces between `<tr>` and `<td>` tags). You can do something like this:

```
$row->find('td')[0];
```

or 

```
$row->first ('td');
```

**Comment by timo002** [comment]
Tnx, after some trying I came up with this myself.

But because the `<td>` elements are children of the `<tr>`, I had expected that it was possible to access them through the `child()` method.

**Comment by Imangazaliev** [comment]
You can use `child()` method if there are no spaces between the `td` tags
