### ISSUE TITLE
Could not load file 

### ISSUE THREAD

**Issue by Haizone** [Imangazaliev/DiDOM#89]
hi itry to use your script but i get that error:
Could not load file http://www.samsungmobile.co.il

this is my code:
`$document = new Document('http://www.samsungmobile.co.il', true);`

**Comment by Imangazaliev** [comment]
Hello. Please check out this issues: #37, #86

**Comment by 5brothers** [comment]
Добрый день

Как возможно спарсить и загрузить файл к себе на сервер? (картинку, например)

**Comment by Imangazaliev** [comment]
@5brothers, привет. Мне кажется, лушче задать этот вопрос на [toster.ru](https://toster.ru) или [stackoverflow.com](https://stackoverflow.com), т. к. он не относится напрямую к DiDOM.

**Comment by 5brothers** [comment]
Спасибо за ответ, я в целом так и подумал и уже нашел способ загрузки изображений при помощи php метода copy(). Просто изучаю новую для себя тему, отсюда и возник вопрос..
