### ISSUE TITLE
Ask question not issue

### ISSUE THREAD

**Issue by oitsuki** [Imangazaliev/DiDOM#90]
Hello,

I would use your script and also I want to scrap a page like amazon on a specific search with title and price.
Below i can do that.

```php
$content = $this->document->loadHtmlFile($url);

var_dump($content->find('*[itemprop=name]'));
var_dump($content->find('*[itemprop=price]'));
```

With this I can see the element, but I want to include in array the price and the name 
it could be.
I don't see how to make that.
Second question curl or not curl ?

```php
$i = 0;

foreach($content as $value) {
==> how to extract inside an array the name and the price of the page ?

$i = $i +1;
return result;
}
```

Thank you for your help.

**Comment by Imangazaliev** [comment]
Hi. I don't understand what you need but I think it is not related to DiDOM. You can ask to question on specialized forums and chats.
