### ISSUE TITLE
Удаление элементов в цикле в дочернем элементе / удаление всех комментариев.

### ISSUE THREAD

**Issue by nepohex** [Imangazaliev/DiDOM#91]
Добрый день! Хочу удалить все комментарии из документа, удаление обычных элементов делаю вот так (не слишком криво ли? другой способ вообще не смог сообразить):

```php
$try = $document->find('.entry'); //Получаю массив элементов
$try_doc = $try[0]->toDocument(); //Конверт в документ

//Удаление из документа (=элемента полной версии документа) всех ненужных мне элементов в цикле

while ($try_doc->find('script')) { 
    $try_doc->first('script')->remove();
}

//Обратная конвертация в элемент
$try_doc = $try_doc->toElement();
//Замена в первоначальном документе элемента с уже удаленными ненужными элементами
$document->first('.entry')->replace($try_elem);
```

А вот как удалить все комментарии в элементе '.entry' - никак не разберусь. Селекторов никаких нету. Пробовал разные итерации типа nextSubling и далее проверку на isCommentNode , но получается вечный цикл: 

```php
while($z = $try[0]->nextSibling()) {
    if ($z->isCommentNode()) {
        //more code to del 
    }
}
```

И вообще общий вопрос - как запустить перебор ВСЕХ элементов документа, и их уже проверять на атрибуты?

**Comment by Imangazaliev** [comment]
Привет.

1. Вместо этого:

```php
$try = $document->find('.entry'); //Получаю массив элементов
$try_doc = $try[0]->toDocument(); //Конверт в документ
```

можно написать так:

```php
$try_doc = $document->first('.entry')->toDocument();
```

2. "не слишком криво ли" - очень криво, лучше сделать так:

```
foreach ($try_doc->find('script') as $scriptEl) { 
    $scriptEl->remove();
}
```

`find()` возвращает массив, который потом итерируется в цикле.

3. Все эти конвертации в документ, а потом обратно в элемент по сути являются костылем. У элемента есть метод `findInDocument()` (который я забыл (или поленился) описать в документации). Этот метод принимает те же аргументы, что и `find()`, но ищет элементы в документе, к которому он сам относится. Т.е. ваш код можно переписать так:

```php
$entryEl = $document->first('.entry')->toDocument();

foreach ($entryEl->findInDocument('script') as $scriptEl) { 
    $scriptEl->remove();
}
```

Если в документе только один элемент к классом `entry`, то можно сделать еще проще:

```php
foreach ($document->findInDocument('.entry script') as $scriptEl) { 
    $scriptEl->remove();
}
```

Если их несколько, то можно указать конкретный элемент с помощью псевдоклассов `first-child`, `last-child` и `nth-child`.

**Comment by nepohex** [comment]
Спасибо за такой подробный ответ! 
`findInDocument()` действительно не хватает, и тем более в хелпе! 

С перебором элементов разобрался. Этой части не хватает в документации, в частности раздела циклов, вот то что мне написали можно прямо туда и закинуть:
**Loop examples**
Remove tags <script> from `DOMDocument`
```
foreach ($document->find('script') as $scriptEl) { 
    $scriptEl->remove();
}
```
Remove tags <script> from `DOMElement`
```
$entryEl = $document->first('.entry');
foreach ($entryEl->findInDocument('script') as $scriptEl) { 
    $scriptEl->remove();
}
```

**Comment by Imangazaliev** [comment]
`findInDocument` он называется потому, что `find` конвертирует элемент в документ и ищет в нем, а `findInDocument` ищет в документе, к которому принадлежит элемент, но в контексте (т.е. внутри) этого элемента. Немного запутано, но если посмотреть код этих методов, то можно понять, о чем я говорю.
