### ISSUE TITLE
Функция concat() ничего не возвращает.

### ISSUE THREAD

**Issue by vlad4ernyshov** [Imangazaliev/DiDOM#93]
Подставлял разные значения, но результат один и тот же - $obj пуст.
```
$obj = $document->xpath('concat("Some text", //ul[@id="gtm-catalog"]/li[not(contains(@class, "hidden"))]/div/ul/li/a)');
    foreach($obj as $arr){
        $data_parser['name'][] = $arr->html();
    }
```
Подскажите, что я делаю не так?

**Comment by Imangazaliev** [comment]
Скиньте, пожалуйста, пример кода, воспроизводящий проблему, чтобы я мог запустить его у себя

**Comment by vlad4ernyshov** [comment]
[test.txt](https://github.com/Imangazaliev/DiDOM/files/1563764/test.txt)


```
$obj = $document->xpath('//ul[@id="gtm-catalog"]/li[not(contains(@class, "hidden"))]/div/ul/li/a | //ul[@id="gtm-catalog"]/li[not(contains(@class, "hidden"))]/div/ul/li/div/ul/li/a | //ul[@id="gtm-catalog"]/li[not(contains(@class, "hidden"))]/div/ul/li/div/ul/li/div/ul/li/a');
foreach($obj as $arr){
    $data_parser['menu_name'][] = $arr->text();
}
```
Этот код ищет названия категорий 3-х уровней вложенности по порядку.
Допустим я хочу объединить некую строку с собранными данными:
```
$obj = $document->xpath('concat("1st-level#", //ul[@id="gtm-catalog"]/li[not(contains(@class, "hidden"))]/div/ul/li/a)');
```
Отдаёт пустоту.

В идеале хочу сделать так (каждый уровень вложенности помечается):
```
$obj = $document->xpath('//ul[@id="gtm-catalog"]/li[not(contains(@class, "hidden"))]/div/ul/li/(concat("1st-level#", a/text())) | //ul[@id="gtm-catalog"]/li[not(contains(@class, "hidden"))]/div/ul/li/div/ul/li/(concat("2nd-level#", a/text())) | //ul[@id="gtm-catalog"]/li[not(contains(@class, "hidden"))]/div/ul/li/div/ul/li/div/ul/li/(concat("3rd-level#", a/text()))');
```
Но тут уже получаю ошибку "DOMXPath::query(): Invalid expression", видимо, где-то не прав.

**Comment by Imangazaliev** [comment]
У класса `DOMXPath` есть два метода: `query`, который возвращает элементы, соответствующие XPath-выражению,  и `evaluate`, который возвращает строку или число. В `find()` используется метод `DOMXPath::query()`. Я не уверен, что вашу задачу можно решить через XPath.
