### ISSUE TITLE
[Question] html tag to xpath

### ISSUE THREAD

**Issue by psociety** [Imangazaliev/DiDOM#95]
Thanks for making this amazing package!
I got a question for you:

I currently have the html tag that i'm looking to grab it's content (ex: `<p style="text-align: justify;">`)
how could i use DiDOM to find by that string or automatically convert that tag to xpath to search for it?

Or will i have to make some hacky thing like?:
```php
$raw = '
<html>
<head>
<title>Im a website</title>
</head>
<body>
<div><h2>Hi</h2></div>
<p>Lorem ipsum</p>
<p style="text-align: justify;">
Im the content that he wants to crawl. I also have <strong>some html tags</strong>.
<img src="http://imgur.com/somewhere.jpg">
</p>
</body>
</html>
';
$html = new Document($raw);
$tmp = new Document('<p style="text-align: justify;"></p>');
$p = $tmp->find('p')[0];

// try to find something that clearly identifies our take, so we can use that look for it
if ($p->attr("id")) {
 $whatIWant = $html->find("#" . $p->attr("id"))[0]->text();
} else if ($p->attr("class")) {
 $whatIWant = $html->find("." . $p->attr("class"))[0]->text();
} else if ($p->attr("style")) {
 $whatIWant = $html->find("p[style='" . $p->attr("class") . "']")[0]->text();
} .. etc
```

**Comment by Imangazaliev** [comment]
Sorry, I don't understand what you want to do.

**Comment by psociety** [comment]
Can didom find by text search?
If not, if i have this string `<p style="text-align: justify;">` could i search for it in some way automatically? our i would have to parse that tag and try to find an identifier/some attribute that i can use to search like i do in the demo code?
