### ISSUE TITLE
Attribute replacement not working

### ISSUE THREAD

**Issue by psociety** [Imangazaliev/DiDOM#96]
**DiDom version:** 1.13
**Code:**
```php
$html = new Document('<html><head></head><body><article><img src="http://old.com"></article></body></html>');
$html = $html->find("article")[0];

foreach ($html->find('img') as &$image) {
    $image->attr("src", "http://new.com");
}
print_r($html->html());
```

**Output:**
`<article><img src="http://old.com"></article>`

**Comment by Imangazaliev** [comment]
The `Element` class has `findInDocument()` method (it [described in Russian documentation](https://github.com/Imangazaliev/DiDOM/blob/master/README-RU.md#Метод-findindocument), but it is not translated to English). This method takes the same arguments as `find()`, but looks for elements in the document to which it refers. That is:

```php
$html = new Document('<html><head></head><body><article><img src="http://old.com"></article></body></html>');

// you can use first() method instead of find('article')[0]
$articleEl = $html->first('article');

foreach ($articleEl->findInDocument('img') as $image) {
    $image->attr('src', 'http://new.com');
}

var_dump($articleEl->html());
```

**Comment by psociety** [comment]
Ty! I didn't know that!
