### ISSUE TITLE
I found bug of the parser

### ISSUE THREAD

**Issue by mezhevikin** [Imangazaliev/DiDOM#97]
Salaam Aleikum, Imangazaliev!
I think, i found bug of the parser.

I made simplified example:

```
$html = "<div class='test'><script>alert(\"<div class='fef'></div>\")</script><div>content</div></div>";
   $document = new Document($html);
   dd($document->first('div.test')->html());
```

Output:

`<div class="test"><script>alert("<div class='fef'></script></div>`

Where did content block disappear?

Thank you for the library!

p.s. Создал issue на английском, чтобы было понятно иностранным пользователям твоей библиотеки.

**Comment by mezhevikin** [comment]
It seems like problem with DOM php extension.
That's too bad.  I can't remove javascript from html string, it needs me.

If someone have same problem, you can use paquettg/php-html-parser.
It library worse than DiDom, but it can work with js.

```
$html = "<div class='test'><script>alert(\"<div class='fef'></div>\")</script><div>content</div></div>";
    $dom = new Dom();
    $dom->setOptions([
	    'removeScripts' => false
    ]);
    $dom->load($html);
    dd($dom->find('div.test')[0]->outerHtml);
```
Output:
```
"<div class='test'><script>alert("<div class='fef'></div>")</script><div>content</div></div>"
```

It is not advertisement, I just want to help.

**Comment by Imangazaliev** [comment]
Wa alaykum salam. You can use regular expression to remove `script` tags from HTML before load it to DiDom.
